@php
    $verticalTerms = [
        'workerSingular' => workcore_term('entity.worker.singular', 'Worker'),
        'workerPlural' => workcore_term('entity.worker.plural', 'Workers'),
        'premisesSingular' => workcore_term('entity.premises.singular', 'Premises'),
        'premisesPlural' => workcore_term('entity.premises.plural', 'Premises'),
        'workOrderSingular' => workcore_term('entity.work_order.singular', 'Work order'),
        'workOrderPlural' => workcore_term('entity.work_order.plural', 'Work orders'),
    ];
@endphp
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>WorkCore {{ $verticalTerms['workerPlural'] }} Availability & Rosters</title>
    <style>
        :root{--ink:#16231f;--muted:#6d7a75;--line:#dfe6e2;--surface:#fff;--canvas:#f4f6f4;--nav:#14251f;--accent:#177b64;--accent-soft:#e5f2ed;--warn:#b9642c;--danger:#a74639;--radius:14px;--shadow:0 18px 45px rgba(25,50,40,.08)}
        *{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select,textarea{font:inherit}.app{min-height:100vh;display:grid;grid-template-columns:250px minmax(0,1fr)}
        .sidebar{background:var(--nav);color:#f8fbf9;padding:24px 18px;display:flex;flex-direction:column;position:sticky;top:0;height:100vh}.brand{display:flex;align-items:center;gap:12px;padding:0 7px 28px}.mark{width:40px;height:40px;border-radius:12px;background:#58c7a7;color:#10221c;display:grid;place-items:center;font-weight:900;font-size:20px}.brand strong,.brand span{display:block}.brand strong{font-size:16px}.brand span{font-size:10px;color:#a9bbb5;margin-top:3px}.nav{display:grid;gap:5px}.nav a{color:#acbdb7;text-decoration:none;padding:11px 12px;border-radius:10px;font-size:13px;font-weight:650}.nav a.active{background:#223a32;color:#fff}.sidebar-card{margin-top:auto;background:#1d342c;border:1px solid #2b493f;border-radius:14px;padding:16px}.sidebar-card span,.sidebar-card small{display:block;color:#adc0ba;font-size:11px}.sidebar-card strong{display:block;margin:6px 0;font-size:19px}.progress{height:6px;border-radius:999px;background:#314b42;overflow:hidden;margin:12px 0}.progress i{display:block;height:100%;width:72%;background:#58c7a7}
        main{min-width:0;padding:28px}.topbar{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.title h1{font-family:Georgia,serif;font-size:34px;font-weight:500;letter-spacing:-.03em;margin:0 0 7px}.title p{margin:0;color:var(--muted);font-size:13px}.actions{display:flex;gap:9px}.btn{border:1px solid transparent;border-radius:9px;padding:10px 14px;font-size:12px;font-weight:750;cursor:pointer}.btn.primary{background:var(--accent);color:#fff}.btn.secondary{background:#fff;border-color:#d8e0dc;color:#2b3834}.btn.danger{background:#fff0ed;border-color:#efc8c0;color:var(--danger)}
        .toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:24px 0 16px}.toolbar select,.toolbar input{height:39px;border:1px solid var(--line);border-radius:9px;background:#fff;padding:0 11px;color:#34423d;font-size:11px}.toolbar select:first-child{min-width:240px}.toolbar .spacer{margin-left:auto}.segmented{display:flex;background:#e4e9e6;padding:3px;border-radius:9px}.segmented button{border:0;background:transparent;padding:8px 11px;border-radius:7px;font-size:11px;font-weight:750;color:#68756f;cursor:pointer}.segmented button.active{background:#fff;color:#1e2d28;box-shadow:0 1px 4px rgba(20,40,30,.12)}
        .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-bottom:16px}.metric{background:#fff;border:1px solid var(--line);border-radius:12px;padding:15px 16px}.metric span,.metric small{display:block;color:#7a8681;font-size:10px}.metric strong{display:block;font-family:Georgia,serif;font-size:28px;font-weight:500;margin:5px 0 3px}.metric.warn{background:#fffaf5;border-color:#efd1bb}.metric.warn strong{color:var(--warn)}
        .panel{background:#fff;border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);overflow:hidden}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:16px 18px;border-bottom:1px solid var(--line)}.panel-head h2{font-family:Georgia,serif;font-weight:500;font-size:22px;margin:0}.panel-head p{color:var(--muted);font-size:11px;margin:4px 0 0}.status{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.05em;padding:6px 8px;border-radius:999px;background:#edf2ef;color:#5e6c66}.status.published{background:#e0f2eb;color:#176c58}.status.cancelled{background:#f9e8e4;color:#a24637}.status.closed{background:#e7e9ed;color:#515b68}
        .roster-wrap{overflow:auto}.grid{min-width:1120px}.grid-head,.worker-row{display:grid;grid-template-columns:190px repeat(7,minmax(130px,1fr))}.grid-head{background:#f8faf8;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:2}.grid-head>div{padding:12px;border-right:1px solid #e7ece9;text-align:center}.grid-head>div:first-child{text-align:left;font-size:10px;font-weight:800;text-transform:uppercase;color:#6e7b76}.day strong,.day span{display:block}.day strong{font-size:11px}.day span{font-size:9px;color:#8b9692;margin-top:2px}.worker-row{min-height:130px;border-bottom:1px solid #e7ece9}.worker{position:sticky;left:0;z-index:1;background:#fff;border-right:1px solid var(--line);padding:13px;display:flex;gap:10px;align-items:flex-start}.avatar{width:36px;height:36px;border-radius:10px;background:#dceee7;color:#176a57;display:grid;place-items:center;font-size:11px;font-weight:850;flex:none}.worker strong,.worker span,.worker small{display:block}.worker strong{font-size:11px}.worker span{font-size:9px;color:#6a7872;margin-top:3px}.worker small{font-size:8px;color:#98a29e;margin-top:4px;text-transform:capitalize}.cell{position:relative;border-right:1px solid #edf0ee;min-height:130px;padding:28px 7px 7px;background-image:linear-gradient(#f1f4f2 1px,transparent 1px);background-size:100% 32px}.availability{position:absolute;top:7px;left:7px;right:7px;font-size:8px;color:#27755f;font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.shift{width:100%;border:1px solid transparent;border-left-width:3px;border-radius:7px;padding:7px;text-align:left;margin-bottom:5px;cursor:pointer;color:#24332e}.shift strong,.shift span,.shift small{display:block}.shift strong{font-size:9px;line-height:1.25;margin:3px 0}.shift span,.shift small{font-size:8px;opacity:.73}.shift.property_management{background:#e4f2ed;border-color:#2e9275}.shift.inspection,.shift.open_home{background:#f0ebf7;border-color:#7d63a4}.shift.maintenance{background:#fff0e1;border-color:#c97733}.shift.cleaning{background:#edf5df;border-color:#829d42}.shift.compliance{background:#f8e9e8;border-color:#b8564b}.shift.office,.shift.leasing{background:#e9eef7;border-color:#5473a1}.shift.on_call,.shift.emergency{background:#f4eedf;border-color:#9a7b2e}.empty{height:100%;min-height:360px;display:grid;place-items:center;text-align:center;color:#7d8a85;padding:40px}.empty h3{font-family:Georgia,serif;color:#30413b;font-size:24px;margin:0 0 7px}.empty p{max-width:420px;font-size:12px;line-height:1.55}
        .availability-table{overflow:auto}.availability-row,.availability-head{display:grid;grid-template-columns:220px repeat(7,minmax(120px,1fr));min-width:1060px}.availability-head{background:#f8faf8}.availability-head div{padding:11px;border-right:1px solid #e6ebe8;font-size:9px;font-weight:800;text-transform:uppercase;color:#71807a;text-align:center}.availability-head div:first-child{text-align:left}.availability-row{border-top:1px solid #e7ece9}.availability-cell{min-height:66px;border:0;border-left:1px solid #e8ecea;background:#fbfcfb;color:#98a29e;font-size:9px;cursor:pointer}.availability-cell.available,.availability-cell.preferred,.availability-cell.on_call{background:#e8f4ef;color:#236c58;font-weight:750}.availability-cell.unavailable{background:#fff0ed;color:#a8513e}
        dialog{border:0;border-radius:16px;padding:0;box-shadow:0 32px 90px rgba(0,0,0,.28);width:min(680px,94vw);max-height:90vh;color:var(--ink)}dialog::backdrop{background:rgba(15,28,23,.58)}.dialog-head{padding:22px 24px 17px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:flex-start}.dialog-head span{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.06em;color:#80908a;font-weight:800}.dialog-head h3{font-family:Georgia,serif;font-weight:500;font-size:23px;margin:5px 0 0}.icon-btn{border:0;background:#eff3f1;width:32px;height:32px;border-radius:8px;cursor:pointer;font-size:18px}.form{padding:20px 24px 24px;display:grid;gap:14px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form-grid.three{grid-template-columns:repeat(3,1fr)}label{display:grid;gap:6px;font-size:10px;font-weight:750;color:#53625c}input,select,textarea{border:1px solid #d8dfdc;border-radius:8px;background:#fff;padding:10px 11px;font-size:11px;color:#26342f}textarea{resize:vertical}.dialog-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:4px}.check{display:flex;align-items:center;gap:8px;font-weight:500}.check input{width:auto}.notice{padding:10px 12px;background:#f5f8f6;border:1px solid #e0e8e4;border-radius:9px;color:#65736e;font-size:10px;line-height:1.45}.toast{position:fixed;left:50%;bottom:24px;transform:translate(-50%,16px);opacity:0;background:#173027;color:#fff;padding:11px 16px;border-radius:9px;font-size:11px;font-weight:750;transition:.2s;z-index:20;pointer-events:none}.toast.show{opacity:1;transform:translate(-50%,0)}.toast.error{background:#9b4939}
        @media(max-width:1100px){.app{grid-template-columns:80px minmax(720px,1fr)}.sidebar{padding:18px 12px}.brand>div:last-child,.nav a{font-size:0}.brand{justify-content:center}.nav a{text-align:center}.sidebar-card{display:none}.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.app{display:block}.sidebar{position:static;height:auto;padding:12px 14px;display:block}.nav,.sidebar-card{display:none}.brand{padding:0;justify-content:flex-start}.brand>div:last-child{display:block}.brand>div:last-child strong{font-size:14px}.brand>div:last-child span{font-size:9px}main{padding:18px 12px}.topbar{display:block}.actions{margin-top:14px}.metrics{grid-template-columns:1fr 1fr}.form-grid,.form-grid.three{grid-template-columns:1fr}.grid-head,.worker-row{grid-template-columns:160px repeat(7,140px)}}
    </style>
</head>
<body>
<div class="app">
    <aside class="sidebar">
        <div class="brand"><div class="mark">W</div><div><strong>WorkCore</strong><span>Property & Service Operations</span></div></div>
        <nav class="nav">
            <a href="#" class="active">▦ &nbsp; Availability & Rosters</a>
            <a href="#">◷ &nbsp; Appointments</a>
            <a href="#">⇢ &nbsp; Dispatch</a>
            <a href="#">⌂ &nbsp; Properties & Premises</a>
            <a href="#">◎ &nbsp; Workers & Skills</a>
        </nav>
        <div class="sidebar-card"><span>Operational coverage</span><strong id="coverageSide">—</strong><div class="progress"><i></i></div><small>Property, office and service-team coverage</small></div>
    </aside>
    <main>
        <header class="topbar">
            <div class="title"><h1>Availability & Rosters</h1><p>Coordinate {{ strtolower($verticalTerms['workerPlural']) }} across {{ strtolower($verticalTerms['premisesPlural']) }}, schedules and service work.</p></div>
            <div class="actions"><button class="btn secondary" id="availabilityBtn">Set availability</button><button class="btn primary" id="newRosterBtn">+ New roster</button></div>
        </header>
        <div class="toolbar">
            <select id="rosterSelect"><option value="">Select a roster</option></select>
            <div class="segmented"><button data-view="roster" class="active">Weekly roster</button><button data-view="availability">Availability</button></div>
            <div class="spacer"></div>
            <select id="workerFilter"><option value="">All {{ strtolower($verticalTerms['workerPlural']) }}</option></select>
            <select id="premisesFilter"><option value="">All {{ strtolower($verticalTerms['premisesPlural']) }}</option></select>
            <button class="btn secondary" id="newShiftBtn">+ Add shift</button>
        </div>
        <section class="metrics">
            <article class="metric"><span>Rostered hours</span><strong id="hoursMetric">0</strong><small>Across visible assignments</small></article>
            <article class="metric"><span>Workers rostered</span><strong id="workersMetric">0</strong><small>Active operational workers</small></article>
            <article class="metric"><span>Property coverage</span><strong id="sitesMetric">0</strong><small>Property or site-days</small></article>
            <article class="metric warn"><span>Coverage gaps</span><strong id="gapsMetric">0</strong><small>Unfilled worker positions</small></article>
        </section>
        <section class="panel" id="panel"><div class="empty"><div><h3>Loading roster data…</h3><p>WorkCore is loading operational workers, properties, availability and roster shifts.</p></div></div></section>
    </main>
</div>
<dialog id="rosterDialog"><div class="dialog-head"><div><span>Create roster</span><h3>Plan operational coverage</h3></div><button class="icon-btn" data-close>×</button></div><form class="form" id="rosterForm">
    <div class="form-grid"><label>Roster name<input name="name" required placeholder="e.g. Parkview operations — Week 31"></label><label>Roster type<select name="roster_type"><option value="property_management">Property management</option><option value="rooming_house">Rooming house</option><option value="office">Office coverage</option><option value="inspection">Inspections</option><option value="maintenance">Maintenance</option><option value="cleaning">Cleaning</option><option value="compliance">Compliance</option><option value="on_call">After-hours / on-call</option><option value="operations">General operations</option></select></label></div>
    <div class="form-grid"><label>Starts on<input type="date" name="starts_on" required></label><label>Ends on<input type="date" name="ends_on" required></label></div>
    <label>Primary {{ strtolower($verticalTerms['premisesSingular']) }}<select name="premises_public_id" id="rosterPremises"><option value="">Across multiple {{ strtolower($verticalTerms['premisesPlural']) }}</option></select></label>
    <label>Notes<textarea name="notes" rows="3" placeholder="Coverage goals, owner requirements, after-hours arrangements…"></textarea></label>
    <div class="dialog-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn primary">Create roster</button></div>
</form></dialog>
<dialog id="shiftDialog"><div class="dialog-head"><div><span>Create shift</span><h3>Add property or service coverage</h3></div><button class="icon-btn" data-close>×</button></div><form class="form" id="shiftForm">
    <div class="form-grid"><label>Shift title<input name="title" required placeholder="e.g. Routine inspections — Docklands"></label><label>Shift type<select name="shift_type"><option value="property_management">Property management</option><option value="inspection">Inspection / viewing</option><option value="open_home">Open home</option><option value="leasing">Leasing</option><option value="maintenance">Maintenance</option><option value="cleaning">Cleaning / turnover</option><option value="compliance">Compliance</option><option value="office">Office coverage</option><option value="on_call">On-call</option><option value="emergency">Emergency response</option></select></label></div>
    <div class="form-grid"><label>{{ $verticalTerms['workerSingular'] }}<select name="worker_public_id" id="shiftWorker"><option value="">Leave unassigned</option></select></label><label>{{ $verticalTerms['premisesSingular'] }}<select name="premises_public_id" id="shiftPremises"><option value="">No single {{ strtolower($verticalTerms['premisesSingular']) }}</option></select></label></div>
    <div class="form-grid"><label>Starts<input type="datetime-local" name="starts_at" required></label><label>Ends<input type="datetime-local" name="ends_at" required></label></div>
    <div class="form-grid"><label>Workers required<input type="number" name="required_worker_count" min="1" max="100" value="1"></label><label>Timezone<input name="timezone" value="{{ $timezone }}" required></label></div>
    <label>Instructions<textarea name="instructions" rows="3" placeholder="Access, resident, owner, safety or service instructions…"></textarea></label>
    <label class="check"><input type="checkbox" name="allow_conflicts" value="1"> Allow a deliberate conflict when an override reason is supplied</label>
    <label>Conflict override reason<textarea name="conflict_override_reason" rows="2"></textarea></label>
    <div class="dialog-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn primary">Create shift</button></div>
</form></dialog>
<dialog id="availabilityDialog"><div class="dialog-head"><div><span>Availability rule</span><h3>Set {{ strtolower($verticalTerms['workerSingular']) }} availability</h3></div><button class="icon-btn" data-close>×</button></div><form class="form" id="availabilityForm">
    <div class="form-grid"><label>{{ $verticalTerms['workerSingular'] }}<select name="worker_public_id" id="availabilityWorker" required></select></label><label>Availability type<select name="availability_type"><option value="available">Available</option><option value="preferred">Preferred</option><option value="on_call">On-call</option><option value="unavailable">Unavailable</option></select></label></div>
    <div class="form-grid three"><label>Weekday<select name="weekday"><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option><option value="7">Sunday</option></select></label><label>From<input type="time" name="starts_at" value="09:00" required></label><label>Until<input type="time" name="ends_at" value="17:00" required></label></div>
    <div class="notice">Availability is checked against roster shifts, Appointments and Dispatch assignments. Managers can override conflicts only with an auditable reason.</div>
    <label>Notes<textarea name="notes" rows="2"></textarea></label>
    <div class="dialog-actions"><button type="button" class="btn secondary" data-close>Cancel</button><button class="btn primary">Save availability</button></div>
</form></dialog>
<div class="toast" id="toast"></div>
<script>
const apiPrefix = '/' + @json($apiPrefix).replace(/^\/+|\/+$/g,'');
const csrf = document.querySelector('meta[name="csrf-token"]').content;
const verticalTerms = @json($verticalTerms);
const state = {rosters:[], roster:null, workers:[], premises:[], availability:[], view:'roster'};
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const requestId = () => (crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`);
async function api(path, options={}){
    const write = options.method && options.method !== 'GET';
    const headers = {'Accept':'application/json',...(write?{'Content-Type':'application/json','X-CSRF-TOKEN':csrf,'Idempotency-Key':requestId(),'X-WorkCore-Confirmation':requestId()}:{}),...(options.headers||{})};
    const response = await fetch(`${apiPrefix}${path}`, {...options, headers});
    const body = await response.json().catch(()=>({}));
    if(!response.ok){throw new Error(body?.errors?.[0]?.detail || body?.message || `Request failed (${response.status})`)}
    return body.data;
}
function attrs(resource){return resource?.attributes ? {id:resource.id,...resource.attributes} : (resource?.public_id ? {id:resource.public_id,...resource} : resource)}
function toast(message,error=false){const t=$('toast');t.textContent=message;t.className=`toast show ${error?'error':''}`;setTimeout(()=>t.className='toast',2800)}
function initials(name){return String(name||'?').split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase()}
function hoursBetween(start,end){return Math.max(0,(new Date(end)-new Date(start))/3600000)}
function localDay(date){return new Date(date).toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short'})}
function dayKey(date){const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function weekDays(){if(!state.roster)return[];const start=new Date(`${state.roster.starts_on}T00:00:00`);return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
function populateSelectors(){
    $('rosterSelect').innerHTML='<option value="">Select a roster</option>'+state.rosters.map(r=>`<option value="${r.id}" ${state.roster?.id===r.id?'selected':''}>${esc(r.name)} · ${esc(r.starts_on)}</option>`).join('');
    const workerOptions=state.workers.map(w=>`<option value="${w.id}">${esc(w.display_name)} — ${esc(w.job_title||w.worker_type)}</option>`).join('');
    $('workerFilter').innerHTML=`<option value="">All ${esc(verticalTerms.workerPlural.toLowerCase())}</option>`+workerOptions;$('shiftWorker').innerHTML='<option value="">Leave unassigned</option>'+workerOptions;$('availabilityWorker').innerHTML=workerOptions;
    const premiseOptions=state.premises.map(p=>`<option value="${p.id}">${esc(p.name)}${p.suburb?' — '+esc(p.suburb):''}</option>`).join('');
    $('premisesFilter').innerHTML=`<option value="">All ${esc(verticalTerms.premisesPlural.toLowerCase())}</option>`+premiseOptions;$('shiftPremises').innerHTML=`<option value="">No single ${esc(verticalTerms.premisesSingular.toLowerCase())}</option>`+premiseOptions;$('rosterPremises').innerHTML=`<option value="">Across multiple ${esc(verticalTerms.premisesPlural.toLowerCase())}</option>`+premiseOptions;
}
function filteredWorkers(){const id=$('workerFilter').value;return state.workers.filter(w=>!id||w.id===id)}
function filteredShifts(){if(!state.roster)return[];const premise=$('premisesFilter').value;return (state.roster.shifts||[]).filter(s=>!premise||s.premises_public_id===premise)}
function updateMetrics(){const shifts=filteredShifts();const assignments=shifts.flatMap(s=>s.assignments||[]);const workerIds=new Set(assignments.map(a=>a.worker_public_id));const siteDays=new Set(shifts.filter(s=>s.premises_public_id).map(s=>`${s.premises_public_id}:${dayKey(s.starts_at)}`));const hours=shifts.reduce((sum,s)=>sum+hoursBetween(s.starts_at,s.ends_at)*Math.max(1,(s.assignments||[]).length),0);const gaps=shifts.reduce((sum,s)=>sum+Math.max(0,Number(s.required_worker_count||1)-(s.assignments||[]).filter(a=>['assigned','accepted'].includes(a.status)).length),0);$('hoursMetric').textContent=hours.toFixed(1);$('workersMetric').textContent=workerIds.size;$('sitesMetric').textContent=siteDays.size;$('gapsMetric').textContent=gaps;$('coverageSide').textContent=`${siteDays.size} site-days`;}
function render(){populateSelectors();updateMetrics();if(state.view==='availability')renderAvailability();else renderRoster()}
function renderRoster(){const panel=$('panel');if(!state.roster){panel.innerHTML='<div class="empty"><div><h3>Create or select a roster</h3><p>Plan weekly coverage for property managers, rooming-house staff, agents, inspectors, cleaners, technicians and contractors.</p></div></div>';return}const days=weekDays();const shifts=filteredShifts();const workers=filteredWorkers();panel.innerHTML=`<div class="panel-head"><div><h2>${esc(state.roster.name)}</h2><p>${esc(state.roster.roster_type.replaceAll('_',' '))} · ${esc(state.roster.starts_on)} to ${esc(state.roster.ends_on)}</p></div><div><span class="status ${esc(state.roster.status)}">${esc(state.roster.status)}</span> ${state.roster.status==='draft'?'<button class="btn primary" id="publishBtn">Publish roster</button>':''}</div></div><div class="roster-wrap"><div class="grid"><div class="grid-head"><div>${esc(verticalTerms.workerSingular)}</div>${days.map(d=>`<div class="day"><strong>${d.toLocaleDateString('en-AU',{weekday:'short'})}</strong><span>${d.toLocaleDateString('en-AU',{day:'numeric',month:'short'})}</span></div>`).join('')}</div>${workers.map(w=>`<div class="worker-row"><div class="worker"><div class="avatar">${initials(w.display_name)}</div><div><strong>${esc(w.display_name)}</strong><span>${esc(w.job_title||w.worker_type)}</span><small>${esc(w.worker_type)}</small></div></div>${days.map(day=>{const key=dayKey(day);const availability=state.availability.filter(a=>a.worker_public_id===w.id&&Number(a.weekday)===((day.getDay()+6)%7+1));const workerShifts=shifts.filter(s=>dayKey(s.starts_at)===key&&(s.assignments||[]).some(a=>a.worker_public_id===w.id));return `<div class="cell"><div class="availability">${availability.length?availability.map(a=>`${a.starts_at?.slice(0,5)||'all day'}–${a.ends_at?.slice(0,5)||''}`).join(', '):'No availability rule'}</div>${workerShifts.map(s=>`<button class="shift ${esc(s.shift_type)}" title="${esc(s.instructions||'')}"><span>${new Date(s.starts_at).toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'})}–${new Date(s.ends_at).toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'})}</span><strong>${esc(s.title)}</strong><small>${esc(s.premises_name||'Portfolio / remote')}</small></button>`).join('')}</div>`}).join('')}</div>`).join('')}</div></div>`;$('publishBtn')?.addEventListener('click',publishRoster)}
function renderAvailability(){const panel=$('panel');const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];panel.innerHTML=`<div class="panel-head"><div><h2>Declared ${esc(verticalTerms.workerSingular.toLowerCase())} availability</h2><p>Recurring operational availability used by Scheduling, Dispatch and roster conflict checks.</p></div><button class="btn primary" id="availabilityAdd">+ Add rule</button></div><div class="availability-table"><div class="availability-head"><div>${esc(verticalTerms.workerSingular)}</div>${days.map(d=>`<div>${d}</div>`).join('')}</div>${filteredWorkers().map(w=>`<div class="availability-row"><div class="worker"><div class="avatar">${initials(w.display_name)}</div><div><strong>${esc(w.display_name)}</strong><span>${esc(w.job_title||w.worker_type)}</span></div></div>${days.map((_,i)=>{const rules=state.availability.filter(a=>a.worker_public_id===w.id&&Number(a.weekday)===i+1);if(!rules.length)return '<button class="availability-cell">Set hours</button>';const primary=rules[0];return `<button class="availability-cell ${esc(primary.availability_type)}">${esc(primary.availability_type.replace('_',' '))}<br>${esc((primary.starts_at||'').slice(0,5))}–${esc((primary.ends_at||'').slice(0,5))}</button>`}).join('')}</div>`).join('')}</div>`;$('availabilityAdd').onclick=()=>openDialog('availabilityDialog')}
async function loadRoster(id){if(!id){state.roster=null;render();return}const data=await api(`/rosters/${id}`);state.roster=attrs(data);render()}
async function loadAll(){try{const [rosters,workers,premises,availability]=await Promise.all([api('/rosters?per_page=100'),api('/workers?per_page=100'),api('/premises?per_page=100'),api('/availability?per_page=100')]);state.rosters=rosters.map(attrs);state.workers=workers.map(attrs);state.premises=premises.map(attrs);state.availability=availability.map(attrs);if(state.rosters[0])await loadRoster(state.rosters[0].id);else render()}catch(error){$('panel').innerHTML=`<div class="empty"><div><h3>Roster API is not available</h3><p>${esc(error.message)}. Enable WorkCore roster routes in the complete MagicAI host.</p></div></div>`;toast(error.message,true)}}
function openDialog(id){$(id).showModal()}document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());
$('rosterSelect').onchange=e=>loadRoster(e.target.value);$('workerFilter').onchange=render;$('premisesFilter').onchange=render;$('newRosterBtn').onclick=()=>openDialog('rosterDialog');$('newShiftBtn').onclick=()=>state.roster?openDialog('shiftDialog'):toast('Create or select a roster first',true);$('availabilityBtn').onclick=()=>openDialog('availabilityDialog');document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));render()});
$('rosterForm').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target).entries());if(!data.premises_public_id)delete data.premises_public_id;try{const result=await api('/rosters',{method:'POST',body:JSON.stringify(data)});event.target.closest('dialog').close();event.target.reset();state.rosters.unshift(attrs(result));await loadRoster(attrs(result).id);toast('Roster created')}catch(error){toast(error.message,true)}};
$('shiftForm').onsubmit=async event=>{event.preventDefault();const fd=new FormData(event.target);const data=Object.fromEntries(fd.entries());data.roster_public_id=state.roster.id;data.required_worker_count=Number(data.required_worker_count||1);data.allow_conflicts=fd.has('allow_conflicts');for(const key of ['worker_public_id','premises_public_id','conflict_override_reason'])if(!data[key])delete data[key];try{await api('/roster-shifts',{method:'POST',body:JSON.stringify(data)});event.target.closest('dialog').close();event.target.reset();await loadRoster(state.roster.id);toast('Roster shift created')}catch(error){toast(error.message,true)}};
$('availabilityForm').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target).entries());data.weekday=Number(data.weekday);data.recurrence_type='weekly';data.timezone=@json($timezone);try{await api('/availability',{method:'POST',body:JSON.stringify(data)});event.target.closest('dialog').close();const availability=await api('/availability?per_page=100');state.availability=availability.map(attrs);render();toast('Availability saved')}catch(error){toast(error.message,true)}};
async function publishRoster(){try{await api(`/rosters/${state.roster.id}/publish`,{method:'POST',body:JSON.stringify({status:'published'})});await loadRoster(state.roster.id);toast('Roster published')}catch(error){if(error.message.includes('uncovered')){const reason=prompt('This roster has coverage gaps. Enter an audit reason to publish deliberately:');if(reason){await api(`/rosters/${state.roster.id}/publish`,{method:'POST',body:JSON.stringify({status:'published',allow_gaps:true,reason})});await loadRoster(state.roster.id);toast('Roster published with recorded coverage gaps')}}else toast(error.message,true)}}
loadAll();
</script>
</body>
</html>
