@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
<div><h4 class="mb-0">Premises incidents — {{ $property->name }}</h4><div class="text-muted">Damage, access, security, welfare, safety and operational incident context.</div></div>
<a class="btn btn-outline-secondary" href="{{ route('managedpremises.properties.show', $property->id) }}">Back</a>
</div>
<div class="alert alert-info"><strong>Work boundary:</strong> ManagedPremises owns incident location, evidence and lifecycle. WorkCore owns maintenance requests, work orders, jobs, scheduling and dispatch.</div>

<div class="card mb-3"><div class="card-header">Report incident</div><div class="card-body"><x-form method="POST" :action="route('managedpremises.properties.incidents.store', $property->id)">@csrf
<div class="row"><div class="col-md-2 form-group"><label>Type</label><select class="form-control" name="incident_type">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseIncident::TYPES as $type)<option value="{{ $type }}">{{ str($type)->replace('_',' ')->title() }}</option>@endforeach</select></div><div class="col-md-2 form-group"><label>Severity</label><select class="form-control" name="severity">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseIncident::SEVERITIES as $severity)<option value="{{ $severity }}" @selected($severity==='medium')>{{ str($severity)->title() }}</option>@endforeach</select></div><div class="col-md-2 form-group"><label>Initial status</label><select class="form-control" name="status"><option value="open">Open</option><option value="triaged">Triaged</option></select></div><div class="col-md-2 form-group"><label>Privacy</label><select class="form-control" name="privacy_level">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseIncident::PRIVACY_LEVELS as $level)<option value="{{ $level }}">{{ str($level)->title() }}</option>@endforeach</select></div><div class="col-md-2 form-group"><label>Space</label><select class="form-control" name="space_id"><option value="">Premise-wide</option>@foreach($spaces as $space)<option value="{{ $space->id }}">{{ $space->name }}</option>@endforeach</select></div><div class="col-md-2 form-group"><label>Occurred</label><input class="form-control" type="datetime-local" name="occurred_at"></div></div>
<div class="row"><div class="col-md-4 form-group"><label>Title</label><input class="form-control" name="title" required maxlength="191"></div><div class="col-md-4 form-group"><label>Related occupancy</label><select class="form-control" name="occupancy_id"><option value="">None</option>@foreach($occupancies as $occupancy)<option value="{{ $occupancy->id }}">{{ $occupancy->display_name }} — {{ optional($occupancy->space)->name }}</option>@endforeach</select></div><div class="col-md-4 form-group"><label>Reported by</label><select class="form-control" name="reported_by_party_role_id"><option value="">Current user / unknown</option>@foreach($partyRoles as $party)<option value="{{ $party->id }}">{{ $party->display_name }}</option>@endforeach</select></div></div>
<div class="form-group"><label>Description</label><textarea class="form-control" name="description" rows="3"></textarea></div><button class="btn btn-primary">Report incident</button>
</x-form></div></div>

@forelse($incidents as $incident)
<div class="card mb-3"><div class="card-header d-flex justify-content-between"><div><strong>#{{ $incident->id }} {{ $incident->title }}</strong> <span class="text-muted">· {{ str($incident->incident_type)->replace('_',' ')->title() }}</span></div><div><span class="badge badge-{{ $incident->severity === 'critical' ? 'danger' : ($incident->severity === 'high' ? 'warning' : 'info') }}">{{ str($incident->severity)->title() }}</span> <span class="badge badge-secondary">{{ str($incident->status)->replace('_',' ')->title() }}</span></div></div>
<div class="card-body"><div class="row mb-3"><div class="col-md-3"><strong>Scope</strong><br>{{ optional($incident->space)->name ?: 'Premise-wide' }}</div><div class="col-md-3"><strong>Reported</strong><br>{{ $incident->reported_at->format('d M Y H:i') }}</div><div class="col-md-3"><strong>Privacy</strong><br>{{ str($incident->privacy_level)->title() }}</div><div class="col-md-3"><strong>WorkCore</strong><br>@if($incident->workcore_reference || $incident->workcore_record_id){{ $incident->workcore_reference ?: $incident->workcore_record_id }} <small>({{ $incident->workcore_status }})</small>@elseNot linked@endif</div></div>
@if($incident->description)<p>{{ $incident->description }}</p>@endif
<div class="row"><div class="col-md-5"><h6>Lifecycle</h6><x-form method="POST" :action="route('managedpremises.properties.incidents.transition', [$property->id, $incident->id])">@csrf<div class="input-group"><select class="form-control" name="status">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Domain\Incidents\IncidentState::allowedTransitions($incident->status) as $status)<option value="{{ $status }}">{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><div class="input-group-append"><button class="btn btn-outline-primary" @disabled(empty(\App\Domains\WorkCore\System\Modules\Premises\Domain\Incidents\IncidentState::allowedTransitions($incident->status)))>Apply</button></div></div></x-form></div>
<div class="col-md-7"><h6>Link existing WorkCore record</h6><x-form method="POST" :action="route('managedpremises.properties.incidents.workcore-link', [$property->id, $incident->id])">@csrf<div class="form-row"><div class="col"><select class="form-control" name="workcore_record_type"><option value="request">Request</option><option value="work_order">Work order</option><option value="job">Job</option><option value="maintenance_case">Maintenance case</option><option value="other">Other</option></select></div><div class="col"><input class="form-control" name="workcore_record_id" placeholder="Record ID"></div><div class="col"><input class="form-control" name="workcore_reference" placeholder="Reference"></div><div class="col-auto"><button class="btn btn-outline-secondary">Link</button></div></div></x-form></div></div>
</div></div>
@empty<div class="card"><div class="card-body text-center text-muted">No incidents.</div></div>@endforelse
@endsection
