<?php

return [
    'enabled' => env('WORKCORE_NATIVE_ENABLED', true),
    'uninstall_policy' => 'retain',
    'runtime_namespace' => 'App\\Domains\\WorkCore',
    'api_middleware' => [
        'api',
        env('WORKCORE_NATIVE_AUTH_MIDDLEWARE', 'auth:api'),
        'workcore.tenant',
        'workcore.api',
    ],
    'approvals' => [
        'signing_key' => env('WORKCORE_CONFIRMATION_SIGNING_KEY'),
        'key_id' => env('WORKCORE_CONFIRMATION_KEY_ID', 'primary'),
        'ttl_seconds' => (int) env('WORKCORE_CONFIRMATION_TTL_SECONDS', 300),
        'enforce_all' => true,
        'allow_legacy_human_confirmation' => false,
    ],
    'entitlements' => [
        'bootstrap_capabilities' => [
            'workcore.core',
            'workcore.tenancy',
            'workcore.authorization',
            'workcore.rewind',
        ],
        'feature_map' => [
            'ext_workcore_core' => [
                'workcore.crm',
                'workcore.catalogue',
                'workcore.support',
                'workcore.knowledge',
                'workcore.reviews',
                'workcore.territories',
            ],
            'ext_workcore_operations' => [
                'workcore.operations',
                'workcore.scheduling',
                'workcore.dispatch',
                'workcore.recurring',
                'workcore.forms',
                'workcore.repairs',
                'workcore.fleet',
            ],
            'ext_workcore_workforce' => [
                'workcore.workforce',
                'workcore.people',
                'workcore.attendance_verification',
                'workcore.rosters',
                'workcore.attendance',
                'workcore.compliance',
                'workcore.assurance',
                'workcore.ndis',
            ],
            'ext_workcore_resources' => [
                'workcore.premises',
                'workcore.assets',
                'workcore.documents',
                'workcore.catalogue',
                'workcore.inventory',
                'workcore.supply',
                'workcore.fleet',
            ],
            'ext_workcore_commercial' => [
                'workcore.finance',
                'workcore.payroll',
                'workcore.inventory',
                'workcore.supply',
                'workcore.vault',
                'workcore.trust_accounting',
            ],
            'ext_workcore_ai_actions' => [
                'workcore.ai',
                'workcore.intelligence',
                'workcore.wizards',
                'workcore.expansion',
            ],
        ],
    ],
];
