<?php

return [
    'enabled' => env('WORKCORE_NATIVE_ENABLED', true),
    'uninstall_policy' => 'retain',
    'runtime_namespace' => 'App\\Domains\\WorkCore',
    'api_middleware' => [
        'api',
        env('WORKCORE_NATIVE_AUTH_MIDDLEWARE', 'auth:api'),
        'workcore.tenant',
        'workcore.api',
    ],
    'approvals' => [
        'signing_key' => env('WORKCORE_CONFIRMATION_SIGNING_KEY'),
        'key_id' => env('WORKCORE_CONFIRMATION_KEY_ID', 'primary'),
        'ttl_seconds' => (int) env('WORKCORE_CONFIRMATION_TTL_SECONDS', 300),
        'enforce_all' => true,
        'allow_legacy_human_confirmation' => false,
    ],
    'entitlements' => [
        'bootstrap_capabilities' => [
            'workcore.core',
            'workcore.tenancy',
            'workcore.authorization',
            'workcore.rewind',
        ],
        'feature_map' => [
            'ext_workcore_core' => [
                'workcore.crm',
                'workcore.catalogue',
                'workcore.support',
                'workcore.knowledge',
                'workcore.reviews',
                'workcore.territories',
            ],
            'ext_workcore_operations' => [
                'workcore.operations',
                'workcore.scheduling',
                'workcore.dispatch',
                'workcore.recurring',
                'workcore.forms',
                'workcore.repairs',
                'workcore.fleet',
                'workcore.trade_compliance',
            ],
            'ext_workcore_workforce' => [
                'workcore.workforce',
                'workcore.people',
                'workcore.recruitment',
                'workcore.onboarding',
                'workcore.people.compliance',
                'workcore.performance',
                'workcore.rosters',
                'workcore.attendance',
                'workcore.attendance.verification',
                'workcore.compliance',
                'workcore.assurance',
            ],
            'ext_workcore_resources' => [
                'workcore.premises',
                'workcore.assets',
                'workcore.accommodation',
                'workcore.documents',
                'workcore.ndis',
            ],
            'ext_workcore_commercial' => [
                'workcore.finance',
                'workcore.money.budgeting',
                'workcore.money.expense_claims',
                'workcore.money.procurement',
                'workcore.money.einvoicing',
                'workcore.money.workforce_loans',
                'workcore.money.sales',
                'workcore.payroll',
                'workcore.inventory',
                'workcore.supply',
                'workcore.vault',
                'workcore.trust_accounting',
            ],
            'ext_workcore_ai_actions' => [
                'workcore.ai',
                'workcore.intelligence',
                'workcore.wizards',
                'workcore.expansion',
            ],
        ],
        'subscription_source' => [
            'companies_table' => env('WORKCORE_MAGICAI_COMPANIES_TABLE', 'tz_companies'),
            'company_user_column' => env('WORKCORE_MAGICAI_COMPANY_USER_COLUMN', 'owner_user_id'),
            'subscriptions_table' => env('WORKCORE_MAGICAI_SUBSCRIPTIONS_TABLE', 'subscriptions'),
            'plans_table' => env('WORKCORE_MAGICAI_PLANS_TABLE', 'plans'),
            'subscription_id_column' => env('WORKCORE_MAGICAI_SUBSCRIPTION_ID_COLUMN', 'id'),
            'subscription_user_column' => env('WORKCORE_MAGICAI_SUBSCRIPTION_USER_COLUMN', 'user_id'),
            'subscription_plan_column' => env('WORKCORE_MAGICAI_SUBSCRIPTION_PLAN_COLUMN', 'plan_id'),
            'status_column' => env('WORKCORE_MAGICAI_SUBSCRIPTION_STATUS_COLUMN', 'status'),
            'valid_from_column' => env('WORKCORE_MAGICAI_SUBSCRIPTION_START_COLUMN', 'starts_at'),
            'valid_until_column' => env('WORKCORE_MAGICAI_SUBSCRIPTION_END_COLUMN', 'ends_at'),
            'updated_at_column' => env('WORKCORE_MAGICAI_SUBSCRIPTION_UPDATED_COLUMN', 'updated_at'),
            'plan_id_column' => env('WORKCORE_MAGICAI_PLAN_ID_COLUMN', 'id'),
            'plan_frequency_column' => env('WORKCORE_MAGICAI_PLAN_FREQUENCY_COLUMN', 'frequency'),
            'plan_updated_at_column' => env('WORKCORE_MAGICAI_PLAN_UPDATED_COLUMN', 'updated_at'),
            'feature_keys' => [
                'ext_workcore_core',
                'ext_workcore_operations',
                'ext_workcore_workforce',
                'ext_workcore_resources',
                'ext_workcore_commercial',
                'ext_workcore_offline',
                'ext_workcore_ai_actions',
            ],
            'active_statuses' => [
                'active',
                'trialing',
                'cancel_at_period_end',
                'bank_approved',
                'banktransfer_approved',
                'bank_renewed',
                'free_approved',
                'stripe_approved',
                'paypal_approved',
                'iyzico_approved',
                'paystack_approved',
                'yokassa_approved',
            ],
            'status_map' => [
                'active' => 'active',
                'trialing' => 'trial',
                'cancel_at_period_end' => 'cancel_at_period_end',
                'bank_approved' => 'active',
                'banktransfer_approved' => 'active',
                'bank_renewed' => 'active',
                'free_approved' => 'active',
                'stripe_approved' => 'active',
                'paypal_approved' => 'active',
                'iyzico_approved' => 'active',
                'paystack_approved' => 'active',
                'yokassa_approved' => 'active',
            ],
        ],
    ],
];
