@extends('layouts.app')
@section('content')
<div class="content-wrapper"><h4>Approval requests — {{ $property->name }}</h4><p class="text-muted">Governed owner and stakeholder decisions. Approval does not execute WorkCore jobs or Titan Money transactions.</p>@include('managedpremises::partials.property-tabs',['property'=>$property])
<div class="row"><div class="col-lg-5"><x-card><x-slot name="header">New approval request</x-slot><x-slot name="body"><x-form method="POST" :action="route('managedpremises.properties.approval-requests.store',$property->id)">@csrf
<div class="form-group"><label>Type</label><select class="form-control" name="request_type">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseApprovalRequest::TYPES as $type)<option value="{{ $type }}">{{ str($type)->replace('_',' ')->title() }}</option>@endforeach</select></div>
<div class="form-group"><label>Title</label><input class="form-control" name="title" maxlength="191" required></div>
<div class="form-group"><label>Summary</label><textarea class="form-control" name="summary" rows="4"></textarea></div>
<div class="form-group"><label>Requested approver</label><select class="form-control" name="requested_party_role_id"><option value="">Internal authorised user</option>@foreach($approvers as $approver)<option value="{{ $approver->id }}">{{ $approver->display_name }} — {{ str($approver->role)->replace('_',' ')->title() }}</option>@endforeach</select></div>
<div class="form-group"><label>Portfolio</label><select class="form-control" name="portfolio_id"><option value="">—</option>@foreach($portfolios as $portfolio)<option value="{{ $portfolio->id }}">{{ $portfolio->name }}</option>@endforeach</select></div>
<div class="form-row"><div class="form-group col"><label>Required approvals</label><input class="form-control" type="number" min="1" max="20" name="required_decisions" value="1"></div><div class="form-group col"><label>Due</label><input class="form-control" type="datetime-local" name="due_at"></div></div>
<label><input type="checkbox" name="submit_now" value="1" checked> Submit immediately</label><div class="mt-3"><button class="btn btn-primary" type="submit">Create request</button></div></x-form></x-slot></x-card></div>
<div class="col-lg-7"><x-card><x-slot name="header">Approval history</x-slot><x-slot name="body">@forelse($requests as $approval)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><div><strong>{{ $approval->title }}</strong><div class="small text-muted">{{ str($approval->request_type)->replace('_',' ')->title() }} @if($approval->requestedPartyRole)· requested from {{ $approval->requestedPartyRole->display_name }}@endif</div></div><span class="badge badge-secondary">{{ str($approval->status)->replace('_',' ')->title() }}</span></div>@if($approval->summary)<p class="mt-2 mb-2">{{ $approval->summary }}</p>@endif<div class="small text-muted">Decisions: {{ $approval->decisions->where('decision','approve')->count() }}/{{ $approval->required_decisions }} approvals @if($approval->due_at)· due {{ $approval->due_at->format('d M Y H:i') }}@endif</div>
@foreach($approval->decisions as $decision)<div class="small mt-1"><strong>{{ ucfirst($decision->decision) }}</strong> · {{ $decision->partyRole?->display_name ?: ('User #'.$decision->user_id) }} @if($decision->note)— {{ $decision->note }}@endif</div>@endforeach
<div class="d-flex flex-wrap mt-2">@if($approval->status==='draft')<x-form method="POST" :action="route('managedpremises.properties.approval-requests.submit',[$property->id,$approval->id])">@csrf<button class="btn btn-sm btn-outline-primary mr-2">Submit</button></x-form>@endif @if($approval->status==='pending')<x-form method="POST" :action="route('managedpremises.properties.approval-requests.decide',[$property->id,$approval->id])">@csrf<input type="hidden" name="decision" value="approve"><button class="btn btn-sm btn-outline-success mr-2">Approve</button></x-form><x-form method="POST" :action="route('managedpremises.properties.approval-requests.decide',[$property->id,$approval->id])">@csrf<input type="hidden" name="decision" value="reject"><button class="btn btn-sm btn-outline-danger mr-2">Reject</button></x-form>@endif @if($approval->status==='approved')<x-form method="POST" :action="route('managedpremises.properties.approval-requests.implement',[$property->id,$approval->id])">@csrf<button class="btn btn-sm btn-outline-primary">Mark implemented</button></x-form>@endif</div></div>@empty<div class="text-muted">No approval requests.</div>@endforelse<div class="mt-3">{{ $requests->links() }}</div></x-slot></x-card></div></div></div>
@endsection
