@php($premisesProfile = app(\App\Domains\WorkCore\System\Modules\Premises\Services\PremisesProfileRegistry::class)->forProperty($property))
<ul class="nav nav-tabs mb-3">
    <li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.show') ? 'active' : '' }}" href="{{ route('managedpremises.properties.show', $property->id) }}">{{ __('managedpremises::pm.property') }}</a></li>
    <li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.plans.*') ? 'active' : '' }}" href="{{ route('managedpremises.plans.index', $property->id) }}">{{ __('managedpremises::pm.service_plans') }}</a></li>
    <li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.visits.*') ? 'active' : '' }}" href="{{ route('managedpremises.visits.index', $property->id) }}">{{ __('managedpremises::pm.visits') }}</a></li>
    <li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.inspections.*') || request()->routeIs('qc-records.*') ? 'active' : '' }}" href="{{ route('qc-records.index', ['property_id' => $property->id]) }}">{{ __('managedpremises::pm.inspections') }}</a></li>
    @if($premisesProfile['features']['agreements'] ?? false)<li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.agreements.*') ? 'active' : '' }}" href="{{ route('managedpremises.properties.agreements.index', $property->id) }}">Agreements</a></li>@endif
    @if($premisesProfile['features']['access_register'] ?? true)<li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.access.*') ? 'active' : '' }}" href="{{ route('managedpremises.properties.access.index', $property->id) }}">Access</a></li>@endif
    @if($premisesProfile['features']['condition_records'] ?? true)<li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.conditions.*') ? 'active' : '' }}" href="{{ route('managedpremises.properties.conditions.index', $property->id) }}">Condition</a></li>@endif
    @if($premisesProfile['features']['incidents'] ?? true)<li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.incidents.*') ? 'active' : '' }}" href="{{ route('managedpremises.properties.incidents.index', $property->id) }}">Incidents</a></li>@endif
    @if($premisesProfile['features']['compliance'] ?? true)<li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.compliance.*') ? 'active' : '' }}" href="{{ route('managedpremises.properties.compliance.index', $property->id) }}">Compliance</a></li>@endif
    <li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.documents.*') ? 'active' : '' }}" href="{{ route('managedpremises.documents.index', $property->id) }}">{{ __('managedpremises::pm.documents') }}</a></li>
    <li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.ownership.*') ? 'active' : '' }}" href="{{ route('managedpremises.properties.ownership.index', $property->id) }}">Ownership</a></li>
    <li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.management-authorities.*') ? 'active' : '' }}" href="{{ route('managedpremises.properties.management-authorities.index', $property->id) }}">Authorities</a></li>
    <li class="nav-item"><a class="nav-link {{ request()->routeIs('managedpremises.properties.approval-requests.*') ? 'active' : '' }}" href="{{ route('managedpremises.properties.approval-requests.index', $property->id) }}">Approvals</a></li>
</ul>
