<?php

return [
    'calendar_feed' => 'managedpremises.api.calendar_feed',
    'safe_operations' => [
        'list_premises',
        'list_premise_spaces',
        'premise_space_tree',
        'premise_space_availability',
        'premise_party_roles',
        'premise_occupancy_summary',
        'premise_vacancy_board',
        'premise_occupancy_history',
        'premise_agreement_register',
        'premise_agreement_expiries',
        'premise_agreement_finance_link_status',
        'premise_access_register_masked',
        'premise_access_custody_history',
        'premise_access_authorisations',
        'premise_physical_access_card_requests_redacted',
        'premise_work_permit_register',
        'premise_work_permit_approval_history',
        'premise_condition_records',
        'premise_open_incidents',
        'premise_incident_workcore_links',
        'premise_compliance_summary',
        'premise_compliance_occurrences',
        'premise_compliance_evidence_status',
        'premise_compliance_rule_pack_provenance',
        'premise_calendar',
        'premise_documents',
        'premise_meter_readings',
        'premise_health_summary',
        'premise_operations_dashboard',
        'premise_operational_alerts',
        'premise_workflow_templates',
        'premise_active_workflows',
        'premise_workflow_history',

        'premise_generative_panels',
        'premise_mobile_workflows',
        'premise_vacancy_listings',
        'premise_portal_grant_summary',
        'public_vacancy_board',
        'premise_vacancy_enquiries',
        'premise_application_pipeline',
        'premise_portal_visible_messages',
        'premise_notice_register',
        'premise_self_service_requests',
        'premise_portfolios',
        'premise_ownership_register',
        'premise_management_authorities',
        'premise_approval_requests',
        'premise_owner_portal_summary',
    ],
];
