<?php

return [
    'owner' => 'ManagedPremises',
    'inspection_owner' => 'QualityControl',
    'money_owner' => 'TitanMoney',
    'maintenance_owner' => 'WorkCore',
    'premise_condition_owner' => 'ManagedPremises',
    'compliance_register_owner' => 'ManagedPremises',
    'legal_interpretation_owner' => 'customer_or_qualified_adviser',
    'boundaries' => [
        'physical_access_card_owner' => 'managed_premises',
        'work_permit_owner' => 'managed_premises',
        'work_permit_execution_owner' => 'workcore',
        'work_permit_document_owner' => 'managed_premises_document_vault',
    ],
    'boot' => [
        'load_routes' => true,
        'load_migrations' => true,
        'register_sidebar' => true,
    ],
    'occupancy' => [
        'history_is_immutable' => true,
        'reservations_consume_capacity' => true,
        'transfers_create_linked_records' => true,
        'space_availability_is_synchronised' => true,
    ],
    'agreements' => [
        'agreement_identity_owner' => 'ManagedPremises',
        'financial_transaction_owner' => 'TitanMoney',
        'renewals_create_linked_records' => true,
        'terminal_agreement_history_is_immutable' => true,
        'finance_links_store_external_references_only' => true,
    ],
    'access' => [
        'secrets_are_encrypted' => true,
        'unmasked_secrets_are_excluded_from_ai_context' => true,
        'custody_changes_create_events' => true,
        'revoked_credentials_are_terminal' => true,
    ],
    'physical_access_cards' => [
        'request_and_item_approval_owner' => 'ManagedPremises',
        'issued_card_custody_owner' => 'ManagedPremises',
        'issued_cards_create_canonical_access_items' => true,
        'card_identifiers_are_excluded_from_untrusted_ai_context' => true,
        'fee_values_and_transactions_belong_to_titan_money' => true,
    ],
    'work_permits' => [
        'permit_scope_and_approval_owner' => 'ManagedPremises',
        'work_execution_owner' => 'WorkCore',
        'approval_decisions_are_append_only' => true,
        'manager_site_and_validation_gates_are_separate' => true,
        'attachments_use_the_existing_document_vault' => true,
        'completed_expired_rejected_and_cancelled_permits_are_terminal' => true,
    ],
    'condition_records' => [
        'premise_condition_owner' => 'ManagedPremises',
    'compliance_register_owner' => 'ManagedPremises',
    'legal_interpretation_owner' => 'customer_or_qualified_adviser',
        'service_quality_inspection_owner' => 'QualityControl',
        'approved_condition_history_is_immutable' => true,
    ],
    'incidents' => [
        'incident_context_owner' => 'ManagedPremises',
        'maintenance_execution_owner' => 'WorkCore',
        'workcore_links_are_external_references' => true,
        'restricted_incidents_require_explicit_permission' => true,
    ],
    'compliance' => [
        'register_owner' => 'ManagedPremises',
        'legal_interpretation_owner' => 'customer_or_qualified_adviser',
        'rule_packs_require_explicit_application' => true,
        'unverified_rule_packs_never_auto_activate' => true,
        'completed_and_waived_occurrences_are_immutable' => true,
        'evidence_verification_requires_authorised_human_review' => true,
        'recurrence_creates_linked_occurrences' => true,
    ],
    'operations' => [
        'dashboard_owner' => 'ManagedPremises',
        'workflow_coordination_owner' => 'ManagedPremises',
        'maintenance_execution_owner' => 'WorkCore',
        'financial_transaction_owner' => 'TitanMoney',
        'legal_interpretation_owner' => 'customer_or_qualified_adviser',
        'workflow_templates_are_profile_configuration' => true,
        'workflow_stage_history_is_append_only' => true,
        'completed_and_cancelled_workflows_are_terminal' => true,
    ],

    'portal' => [
        'grant_owner' => 'ManagedPremises',
        'authentication_integration_owner' => 'host_application',
        'tokens_are_one_way_hashed' => true,
        'tokens_are_never_returned_after_initial_issue' => true,
        'access_secrets_and_finance_identifiers_are_excluded' => true,
        'revoked_and_expired_grants_are_terminal' => true,
    ],
    'vacancies' => [
        'listing_owner' => 'ManagedPremises',
        'external_channel_delivery_owner' => 'channel_integration',
        'human_approval_required_before_publication' => true,
        'publication_payloads_are_immutable_snapshots' => true,
        'exact_address_requires_explicit_opt_in' => true,
        'channel_credentials_are_not_stored' => true,
    ],
    'applications' => [
        'enquiry_owner' => 'ManagedPremises',
        'application_pipeline_owner' => 'ManagedPremises',
        'application_conversion_owner' => 'managed_premises_authorised_operator',
        'occupancy_creation_requires_explicit_conversion' => true,
        'terminal_application_history_is_immutable' => true,
    ],
    'communications' => [
        'message_history_owner' => 'ManagedPremises',
        'internal_notes_are_never_portal_visible' => true,
        'notice_issue_requires_human_approval' => true,
        'issued_notice_content_is_immutable' => true,
    ],
    'self_service_requests' => [
        'request_context_owner' => 'ManagedPremises',
        'maintenance_execution_owner' => 'WorkCore',
        'workcore_links_are_external_references' => true,
        'closed_request_history_is_immutable' => true,
    ],
    'portfolio_ownership' => [
        'portfolio_owner' => 'ManagedPremises',
        'ownership_register_owner' => 'ManagedPremises',
        'legal_title_interpretation_owner' => 'customer_or_qualified_adviser',
        'financial_statement_owner' => 'TitanMoney',
        'dated_membership_and_ownership_history_is_preserved' => true,
        'active_percentage_shares_cannot_exceed_100' => true,
    ],
    'management_authorities' => [
        'operational_authority_owner' => 'ManagedPremises',
        'legal_validity_owner' => 'customer_or_qualified_adviser',
        'monetary_policy_owner' => 'TitanMoney',
        'activation_requires_approval' => true,
        'ended_rejected_and_cancelled_history_is_terminal' => true,
    ],
    'stakeholder_approvals' => [
        'approval_register_owner' => 'ManagedPremises',
        'work_execution_owner' => 'WorkCore',
        'financial_execution_owner' => 'TitanMoney',
        'decisions_are_append_only' => true,
        'human_decision_is_required' => true,
        'approval_does_not_execute_linked_action' => true,
    ],
    'generative_ui' => [
        'panel_schema_owner' => 'ManagedPremises',
        'renderer_owner' => 'AIChatPro',
        'actions_use_existing_domain_services' => true,
        'panels_do_not_bypass_permissions_or_approvals' => true,
    ],
    'mobile' => [
        'workflow_data_owner' => 'ManagedPremises',
        'client_renderer_owner' => 'ChatbotPWA_or_TitanGo',
        'assignment_scope_is_enforced' => true,
        'protected_data_is_redacted' => true,
    ],
    'compatibility' => [
        'legacy_inspection_routes_redirect_to_quality_control' => true,
    ],
];
