<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><title>{{ $portal['premise']['name'] ?? 'Premises portal' }}</title><style>body{font-family:system-ui,sans-serif;background:#f4f6f8;margin:0;color:#20242a}.wrap{max-width:760px;margin:auto;padding:20px}.card{background:white;border-radius:12px;padding:18px;margin-bottom:16px;box-shadow:0 1px 4px #0002}.muted{color:#667085}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.pill{display:inline-block;background:#eef2f6;border-radius:999px;padding:4px 9px;margin:2px;font-size:12px}label{display:block;margin-top:10px;font-weight:600}input,select,textarea,button{width:100%;box-sizing:border-box;padding:10px;margin-top:4px;border:1px solid #ccd2d8;border-radius:8px}button{background:#20242a;color:white;cursor:pointer}</style></head>
<body><main class="wrap">
    <div class="card"><h1>{{ $portal['premise']['name'] ?? 'Premises portal' }}</h1><div class="muted">Secure scoped access · expires {{ $portal['grant']['expires_at'] ? \Carbon\Carbon::parse($portal['grant']['expires_at'])->format('d M Y') : 'when revoked' }}</div></div>
    @if(session('success'))<div class="card">{{ session('success') }}</div>@endif
    <div class="grid">
        @isset($portal['space'])<div class="card"><h3>Space</h3><strong>{{ $portal['space']['name'] ?? '—' }}</strong><div class="muted">{{ str($portal['space']['space_type'] ?? 'space')->replace('_',' ')->title() }}</div></div>@endisset
        @isset($portal['occupancy'])<div class="card"><h3>Occupancy</h3><strong>{{ str($portal['occupancy']['status'] ?? '')->replace('_',' ')->title() }}</strong><div class="muted">{{ $portal['occupancy']['start_date'] ?? '' }} @if(!empty($portal['occupancy']['end_date']))– {{ $portal['occupancy']['end_date'] }}@endif</div></div>@endisset
        @isset($portal['agreement'])<div class="card"><h3>Agreement</h3><strong>{{ $portal['agreement']['title'] ?? 'Agreement' }}</strong><div class="muted">{{ str($portal['agreement']['status'] ?? '')->replace('_',' ')->title() }}</div></div>@endisset
    </div>
    @if(!empty($portal['workflows']))<div class="card"><h2>Progress</h2>@foreach($portal['workflows'] as $workflow)<div style="margin-bottom:14px"><strong>{{ $workflow['title'] }}</strong><div class="muted">{{ $workflow['current_stage'] }} · {{ $workflow['completion_percent'] }}%</div><progress style="width:100%" max="100" value="{{ $workflow['completion_percent'] }}"></progress></div>@endforeach</div>@endif
    @if(!empty($portal['access_authorisations']))<div class="card"><h2>Access authorisations</h2>@foreach($portal['access_authorisations'] as $authorisation)<div><strong>{{ $authorisation['purpose'] ?: 'Authorised access' }}</strong><div class="muted">{{ $authorisation['access_scope'] }} @if(!empty($authorisation['ends_at']))· ends {{ $authorisation['ends_at'] }}@endif</div></div>@endforeach</div>@endif
    @if(isset($portal['messages']))<div class="card"><h2>Messages</h2>@forelse($portal['messages'] as $message)<div style="margin-bottom:12px"><strong>{{ $message->direction === 'inbound' ? 'You' : 'Manager' }}</strong><div>{{ $message->body }}</div><div class="muted">{{ optional($message->sent_at)->format('d M Y H:i') }}</div></div>@empty<div class="muted">No messages yet.</div>@endforelse@if(in_array('send_message',$portal['grant']['capabilities'] ?? [],true))<form method="POST" action="{{ route('managedpremises.public.portal.messages.store',$token) }}">@csrf<label>New message</label><textarea name="body" rows="4" maxlength="10000" required></textarea><button type="submit">Send message</button></form>@endif</div>@endif
    @if(isset($portal['notices']))<div class="card"><h2>Notices</h2>@forelse($portal['notices'] as $notice)<div style="margin-bottom:14px"><strong>{{ $notice->title }}</strong><div>{{ $notice->body }}</div><div class="muted">Issued {{ optional($notice->issued_at)->format('d M Y') }}</div>@if($notice->requires_acknowledgement && !$notice->acknowledged_at && in_array('acknowledge_notice',$portal['grant']['capabilities'] ?? [],true))<form method="POST" action="{{ route('managedpremises.public.portal.notices.acknowledge',[$token,$notice->id]) }}">@csrf<button type="submit">Acknowledge</button></form>@endif</div>@empty<div class="muted">No current notices.</div>@endforelse</div>@endif
    @if(!empty($portal['owner_summary']))<div class="card"><h2>Owner / manager summary</h2>@foreach($portal['owner_summary']['ownership'] ?? [] as $interest)<div><strong>{{ str($interest['ownership_type'])->replace('_',' ')->title() }}</strong><span class="muted"> · {{ $interest['share_percent'] !== null ? rtrim(rtrim(number_format((float)$interest['share_percent'],4),'0'),'.').'%' : 'share unspecified' }}</span></div>@endforeach @foreach($portal['owner_summary']['management_authorities'] ?? [] as $authority)<div style="margin-top:8px"><strong>{{ str($authority['authority_type'])->replace('_',' ')->title() }}</strong><div class="muted">{{ str($authority['status'])->replace('_',' ')->title() }}</div></div>@endforeach<div class="muted" style="margin-top:10px">{{ $portal['owner_summary']['financial_boundary'] }}</div></div>@endif
    @if(!empty($portal['portfolio']))<div class="card"><h2>{{ $portal['portfolio']['name'] ?? 'Portfolio' }}</h2><div class="muted">{{ $portal['portfolio']['premise_count'] }} premises</div>@foreach($portal['portfolio']['premises'] ?? [] as $premise)<div style="margin-top:10px"><strong>{{ $premise['name'] }}</strong><div class="muted">{{ str($premise['profile_key'])->replace('_',' ')->title() }} · {{ $premise['occupied_spaces'] }} occupied · {{ $premise['available_spaces'] }} available</div></div>@endforeach</div>@endif
    @if(isset($portal['approval_requests']))<div class="card"><h2>Approval requests</h2>@forelse($portal['approval_requests'] as $approval)<div style="margin-bottom:14px"><strong>{{ $approval->title }}</strong><div>{{ $approval->summary }}</div><div class="muted">{{ str($approval->status)->replace('_',' ')->title() }} @if($approval->due_at)· due {{ $approval->due_at->format('d M Y') }}@endif</div>@if($approval->status==='pending' && in_array('decide_approval_requests',$portal['grant']['capabilities'] ?? [],true))<div class="grid"><form method="POST" action="{{ route('managedpremises.public.portal.approvals.decide',[$token,$approval->id]) }}">@csrf<input type="hidden" name="decision" value="approve"><button type="submit">Approve</button></form><form method="POST" action="{{ route('managedpremises.public.portal.approvals.decide',[$token,$approval->id]) }}">@csrf<input type="hidden" name="decision" value="reject"><button type="submit">Reject</button></form></div>@endif</div>@empty<div class="muted">No approval requests.</div>@endforelse</div>@endif
    @if(isset($portal['requests']))<div class="card"><h2>Your requests</h2>@forelse($portal['requests'] as $serviceRequest)<div style="margin-bottom:10px"><strong>{{ $serviceRequest->title }}</strong><div class="muted">{{ $serviceRequest->request_number }} · {{ str($serviceRequest->status)->replace('_',' ')->title() }}</div></div>@empty<div class="muted">No requests yet.</div>@endforelse@if(in_array('submit_request',$portal['grant']['capabilities'] ?? [],true))<form method="POST" action="{{ route('managedpremises.public.portal.requests.store',$token) }}">@csrf<label>Request type</label><select name="request_type">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseSelfServiceRequest::TYPES as $type)<option value="{{ $type }}">{{ str($type)->replace('_',' ')->title() }}</option>@endforeach</select><label>Priority</label><select name="priority"><option value="low">Low</option><option value="normal" selected>Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><label>Title</label><input name="title" required maxlength="191"><label>Details</label><textarea name="description" rows="5" maxlength="10000"></textarea><button type="submit">Submit request</button></form>@endif</div>@endif
    @if(in_array('submit_incident', $portal['grant']['capabilities'] ?? [], true))<div class="card"><h2>Report an issue</h2><form method="POST" action="{{ route('managedpremises.public.portal.incidents.store', $token) }}">@csrf<label>Type</label><select name="incident_type" required>@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseIncident::TYPES as $type)<option value="{{ $type }}">{{ str($type)->replace('_',' ')->title() }}</option>@endforeach</select><label>Urgency</label><select name="severity"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option></select><label>Title</label><input name="title" required maxlength="191"><label>Details</label><textarea name="description" rows="5" maxlength="5000"></textarea><button type="submit">Submit report</button></form></div>@endif
    <div class="muted" style="font-size:12px;text-align:center">This link is personal and revocable. Do not forward it.</div>
</main></body></html>
