<?php

declare(strict_types=1);

return [
    'enabled' => true,
    'version' => '0.8.1',
    'schema_version' => '1.6',

    'features' => [
        'extension_shell' => true,
        'health' => true,
        'unified_action_contracts' => true,
        'generative_ui_contracts' => true,
        'strict_company_context_contract' => true,
        'permission_catalogue' => true,
        'money_primitives' => true,
        'number_sequence_foundation' => true,
        'idempotency_foundation' => true,
        'financial_document_snapshots' => true,
        'company_financial_settings' => true,
        'donor_consolidation' => true,
        'commercial_document_schema' => true,
        'invoices' => true,
        'payments' => true,
        'quotes' => true,
        'expenses' => true,
        'ledger' => true,
        'gst_posting_and_reporting' => true,
        'receivables_ageing' => true,
        'payables' => true,
        'bank_reconciliation' => true,
        'cashflow_forecasting' => true,
        'job_profitability' => true,
        'accountant_exports' => true,
        'autonomous_money_management' => true,
        'auto_invoice_eligibility' => true,
        'payment_qr_contracts' => true,
        'collection_sequences' => true,
        'runtime_persistence_adapters' => true,
        'automatic_invoice_runtime' => true,
        'workcore_completion_listener' => true,
        'balanced_invoice_posting_runtime' => true,
        'qr_svg_rendering' => true,
        'titan_talk_delivery_outbox' => true,
        'pulse_collection_scheduling' => true,
        'aichatpro_invoice_tool' => true,
        'chatbot_invoice_card' => true,
        'collection_execution_runtime' => true,
        'collection_suppression_runtime' => true,
        'payment_evidence_ingestion' => true,
        'payment_match_runtime' => true,
        'automatic_payment_allocation' => true,
        'manual_payment_match_confirmation' => true,
        'receipt_runtime' => true,
        'reconciliation_exception_runtime' => true,
        'aichatpro_payment_tool' => true,
        'chatbot_payment_card' => true,
        'pulse_worker_runtime' => true,
        'titan_signal_outbox_relay' => true,
        'titan_talk_delivery_worker' => true,
        'device_payment_evidence_adapter' => true,
        'paypal_settlement_webhook_runtime' => true,
        'australian_bank_csv_import' => true,
        'strict_reconciliation_closure' => true,
        'budget_control' => true,
        'budget_actuals_and_variance' => true,
        'budget_forecast_scenarios' => true,
        'expense_claims_and_reimbursements' => true,
        'procurement_and_purchase_receipts' => true,
        'supplier_credits' => true,
        'electronic_invoicing' => true,
        'workforce_loans_and_advances' => true,
        'pos_split_settlement' => true,
        'field_sales_orders' => true,
        'production_ready' => false,
    ],

    'interfaces' => [
        'aichatpro' => true,
        'chatbot_pwa' => true,
        'chatbot_customer' => true,
        'ai_agent' => true,
        'pulse' => true,
        'api' => true,
        'web' => true,
    ],

    'defaults' => [
        'country_code' => 'AU',
        'base_currency' => 'AUD',
        'timezone' => 'Australia/Melbourne',
        'financial_year_start_month' => 7,
        'financial_year_start_day' => 1,
        'payment_terms_days' => 7,
        'prices_include_tax' => true,
        'gst_accounting_basis' => 'cash',
    ],

    'currencies' => [
        'AUD' => ['minor_units' => 2],
        'NZD' => ['minor_units' => 2],
        'USD' => ['minor_units' => 2],
        'CAD' => ['minor_units' => 2],
        'GBP' => ['minor_units' => 2],
        'EUR' => ['minor_units' => 2],
        'JPY' => ['minor_units' => 0],
    ],

    'sequence_defaults' => [
        'estimate' => ['prefix' => 'EST-', 'padding' => 6],
        'quote' => ['prefix' => 'Q-', 'padding' => 6],
        'invoice' => ['prefix' => 'INV-', 'padding' => 6],
        'credit_note' => ['prefix' => 'CN-', 'padding' => 6],
        'receipt' => ['prefix' => 'RCT-', 'padding' => 6],
        'expense' => ['prefix' => 'EXP-', 'padding' => 6],
        'supplier_bill' => ['prefix' => 'BILL-', 'padding' => 6],
        'purchase_order' => ['prefix' => 'PO-', 'padding' => 6],
        'reimbursement_batch' => ['prefix' => 'RB-', 'padding' => 6],
        'pos_sale' => ['prefix' => 'SALE-', 'padding' => 8],
        'sales_order' => ['prefix' => 'SO-', 'padding' => 6],
        'journal' => ['prefix' => 'JRN-', 'padding' => 8],
    ],

    'risk_defaults' => [
        'read' => 'low',
        'draft' => 'medium',
        'external_write' => 'high',
        'irreversible_financial_write' => 'critical',
    ],

    'autonomy' => [
        'default_level' => 'approve',
        'automatic_match_threshold' => 95,
        'automatic_amount_limit_minor' => 50000,
        'collection_sequence' => [
            ['day' => -3, 'code' => 'due_soon', 'tone' => 'helpful', 'channels' => ['email', 'chatbot']],
            ['day' => 0, 'code' => 'due_today', 'tone' => 'friendly', 'channels' => ['email', 'chatbot']],
            ['day' => 3, 'code' => 'friendly_reminder', 'tone' => 'friendly', 'channels' => ['email', 'sms']],
            ['day' => 7, 'code' => 'direct_reminder', 'tone' => 'direct', 'channels' => ['email', 'sms', 'chatbot']],
            ['day' => 14, 'code' => 'firm_reminder', 'tone' => 'firm', 'channels' => ['email', 'task']],
            ['day' => 21, 'code' => 'payment_plan_offer', 'tone' => 'supportive', 'channels' => ['email', 'task'], 'approval_required' => true],
            ['day' => 30, 'code' => 'escalation_review', 'tone' => 'escalation', 'channels' => ['task'], 'approval_required' => true],
        ],
        'suppressions' => ['dispute_open', 'payment_plan_active', 'payment_claim_pending', 'paused', 'paid', 'voided', 'credited'],
    ],

    'dependencies' => [
        'required' => [
            'laravel' => Illuminate\Foundation\Application::class,
            'qr-renderer' => BaconQrCode\Writer::class,
        ],
        'optional' => [
            'platform-core' => App\Providers\PlatformCoreServiceProvider::class,
            'aichatpro' => App\Extensions\AIChatPro\System\AIChatProServiceProvider::class,
            'chatbot' => App\Extensions\Chatbot\System\ChatbotServiceProvider::class,
            'ai-agent' => App\Extensions\AIAgent\System\AIAgentServiceProvider::class,
            'xero' => App\Extensions\Xero\System\XeroServiceProvider::class,
            'titan-docs' => App\Extensions\TitanDocs\System\TitanDocsServiceProvider::class,
            'titan-pulse' => App\Extensions\TitanPulse\System\TitanPulseServiceProvider::class,
            'titan-talk' => App\Extensions\TitanTalk\System\TitanTalkServiceProvider::class,
        ],
    ],
];
