<?php

declare(strict_types=1);
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
Schema::create('tz_wizard_definitions',function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->unsignedBigInteger('company_id')->nullable()->index();$t->string('definition_key',150);$t->unsignedInteger('version')->default(1);$t->string('title');$t->text('description')->nullable();$t->string('status',30)->default('draft')->index();$t->json('definition');$t->unsignedBigInteger('created_by_user_id')->nullable();$t->unsignedBigInteger('updated_by_user_id')->nullable();$t->timestamp('published_at')->nullable();$t->timestamps();$t->unique(['company_id','definition_key','version'],'tz_wizard_definition_version_unique');});
Schema::create('tz_wizard_runs',function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->unsignedBigInteger('company_id')->index();$t->string('definition_key',150)->index();$t->unsignedInteger('definition_version')->default(1);$t->string('status',30)->default('draft')->index();$t->string('mode',30)->default('hybrid');$t->string('current_section_key',150)->nullable();$t->string('current_question_key',255)->nullable();$t->unsignedBigInteger('initiated_by_user_id');$t->ulid('assisted_by_agent_public_id')->nullable();$t->decimal('completion_percent',5,2)->default(0);$t->json('metadata')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('paused_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
Schema::create('tz_wizard_answers',function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->unsignedBigInteger('company_id')->index();$t->foreignId('run_id')->constrained('tz_wizard_runs')->cascadeOnDelete();$t->string('question_key',255);$t->json('value')->nullable();$t->string('source',40)->default('user_entered');$t->decimal('confidence',5,4)->nullable();$t->boolean('is_confirmed')->default(false);$t->unsignedBigInteger('answered_by_user_id')->nullable();$t->ulid('answered_by_agent_public_id')->nullable();$t->timestamps();$t->unique(['run_id','question_key'],'tz_wizard_answer_unique');});
Schema::create('tz_wizard_section_approvals',function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->unsignedBigInteger('company_id')->index();$t->foreignId('run_id')->constrained('tz_wizard_runs')->cascadeOnDelete();$t->string('section_key',150);$t->string('status',30)->default('pending');$t->json('summary')->nullable();$t->unsignedBigInteger('approved_by_user_id')->nullable();$t->timestamp('approved_at')->nullable();$t->text('rejected_reason')->nullable();$t->timestamps();$t->unique(['run_id','section_key'],'tz_wizard_section_approval_unique');});
Schema::create('tz_wizard_events',function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->unsignedBigInteger('company_id')->index();$t->foreignId('run_id')->constrained('tz_wizard_runs')->cascadeOnDelete();$t->string('event_type',150)->index();$t->json('payload')->nullable();$t->string('actor_type',30);$t->string('actor_public_id',100)->nullable();$t->timestamp('created_at')->useCurrent();});
Schema::create('tz_wizard_action_results',function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->unsignedBigInteger('company_id')->index();$t->foreignId('run_id')->constrained('tz_wizard_runs')->cascadeOnDelete();$t->string('action_key',180);$t->string('risk',20);$t->string('status',30)->default('draft');$t->json('request_payload')->nullable();$t->json('result_payload')->nullable();$t->ulid('approval_public_id')->nullable();$t->timestamp('executed_at')->nullable();$t->timestamps();});
} public function down():void{foreach(['tz_wizard_action_results','tz_wizard_events','tz_wizard_section_approvals','tz_wizard_answers','tz_wizard_runs','tz_wizard_definitions'] as $table)Schema::dropIfExists($table);} };
