<?php

declare(strict_types=1);

$section = static fn (
    string $menuKey,
    string $label,
    string $icon,
    string $routeName,
    string $path,
    int $order,
    array $capabilities,
    string $description,
): array => compact('menuKey', 'label', 'icon', 'routeName', 'path', 'order', 'capabilities', 'description');

$workspace = static fn (
    string $menuKey,
    string $label,
    string $icon,
    string $routeName,
    string $path,
    int $order,
    array $capabilities,
    string $description,
    array $sections,
): array => compact('menuKey', 'label', 'icon', 'routeName', 'path', 'order', 'capabilities', 'description', 'sections');

return [
    'crm' => $workspace(
        'workcore_crm_dropdown',
        'CRM',
        'tabler-users-group',
        'dashboard.user.workcore.crm.index',
        'crm',
        40,
        ['workcore.crm'],
        'Customers, contacts, leads, pipelines and relationship activity.',
        [
            'customers' => $section('workcore_crm_customers', 'Customers', 'tabler-building-community', 'dashboard.user.workcore.crm.customers.index', 'crm/customers', 10, ['workcore.crm'], 'Service-recipient organisations and customer records.'),
            'contacts' => $section('workcore_crm_contacts', 'Contacts', 'tabler-address-book', 'dashboard.user.workcore.crm.contacts.index', 'crm/contacts', 20, ['workcore.crm'], 'People linked to customers, leads and opportunities.'),
            'leads' => $section('workcore_crm_leads', 'Leads', 'tabler-user-search', 'dashboard.user.workcore.crm.leads.index', 'crm/leads', 30, ['workcore.crm'], 'Prospects, lead status and conversion readiness.'),
            'pipelines' => $section('workcore_crm_pipelines', 'Pipelines', 'tabler-layout-kanban', 'dashboard.user.workcore.crm.pipelines.index', 'crm/pipelines', 40, ['workcore.crm'], 'Sales stages and opportunity flow.'),
            'opportunities' => $section('workcore_crm_opportunities', 'Opportunities', 'tabler-coin', 'dashboard.user.workcore.crm.opportunities.index', 'crm/opportunities', 50, ['workcore.crm'], 'Qualified opportunities, values, stages and outcomes.'),
            'activities' => $section('workcore_crm_activities', 'Activities', 'tabler-list-check', 'dashboard.user.workcore.crm.activities.index', 'crm/activities', 60, ['workcore.crm'], 'Calls, follow-ups, notes and customer interactions.'),
            'reports' => $section('workcore_crm_reports', 'CRM Reports', 'tabler-chart-bar', 'dashboard.user.workcore.crm.reports.index', 'crm/reports', 70, ['workcore.crm'], 'Pipeline, conversion and relationship reporting.'),
        ],
    ),
    'operations' => $workspace(
        'workcore_operations_dropdown',
        'Operations',
        'tabler-briefcase',
        'dashboard.user.workcore.operations.index',
        'operations',
        50,
        ['workcore.operations'],
        'Work orders, scheduling, dispatch and field-service delivery.',
        [
            'work-orders' => $section('workcore_operations_work_orders', 'Work Orders', 'tabler-clipboard-list', 'dashboard.user.workcore.operations.work-orders.index', 'operations/work-orders', 10, ['workcore.operations'], 'Jobs, work orders, status and operational delivery.'),
            'schedule' => $section('workcore_operations_schedule', 'Schedule', 'tabler-calendar-event', 'dashboard.user.workcore.operations.schedule.index', 'operations/schedule', 20, ['workcore.scheduling'], 'Appointments, service windows and scheduling context.'),
            'dispatch' => $section('workcore_operations_dispatch', 'Dispatch', 'tabler-route', 'dashboard.user.workcore.operations.dispatch.index', 'operations/dispatch', 30, ['workcore.dispatch'], 'Assignments, crews, readiness and dispatch decisions.'),
            'territories' => $section('workcore_operations_territories', 'Map and Territories', 'tabler-map-2', 'dashboard.user.workcore.operations.territories.index', 'operations/territories', 40, ['workcore.territories'], 'Branches, territories and geographic responsibility.'),
            'recurring' => $section('workcore_operations_recurring', 'Recurring Services', 'tabler-repeat', 'dashboard.user.workcore.operations.recurring.index', 'operations/recurring', 50, ['workcore.recurring'], 'Recurring agreements, visits and service generation.'),
            'service-sites' => $section('workcore_operations_service_sites', 'Service Sites', 'tabler-building', 'dashboard.user.workcore.operations.service-sites.index', 'operations/service-sites', 60, ['workcore.premises'], 'Customer premises and operational service locations.'),
            'forms' => $section('workcore_operations_forms', 'Forms and Checklists', 'tabler-forms', 'dashboard.user.workcore.operations.forms.index', 'operations/forms', 70, ['workcore.forms'], 'Operational forms, checklists and completion evidence.'),
            'compliance' => $section('workcore_operations_compliance', 'Inspections and Compliance', 'tabler-shield-check', 'dashboard.user.workcore.operations.compliance.index', 'operations/compliance', 80, ['workcore.compliance', 'workcore.trade_compliance'], 'Inspections, hazards, incidents and corrective actions.'),
            'reports' => $section('workcore_operations_reports', 'Operations Reports', 'tabler-chart-dots', 'dashboard.user.workcore.operations.reports.index', 'operations/reports', 90, ['workcore.operations'], 'Operational throughput, completion and service reporting.'),
        ],
    ),
    'workforce' => $workspace(
        'workcore_workforce_dropdown',
        'Workforce',
        'tabler-users',
        'dashboard.user.workcore.workforce.index',
        'workforce',
        60,
        ['workcore.workforce'],
        'Workers, rosters, attendance and workforce assurance.',
        [
            'people' => $section('workcore_workforce_people', 'Workers and People', 'tabler-user-circle', 'dashboard.user.workcore.workforce.people.index', 'workforce/people', 10, ['workcore.workforce', 'workcore.people'], 'Workers, employment records and operational identities.'),
            'rosters' => $section('workcore_workforce_rosters', 'Rosters', 'tabler-calendar-week', 'dashboard.user.workcore.workforce.rosters.index', 'workforce/rosters', 20, ['workcore.rosters'], 'Rosters, shifts, availability and team coverage.'),
            'attendance' => $section('workcore_workforce_attendance', 'Attendance', 'tabler-clock-check', 'dashboard.user.workcore.workforce.attendance.index', 'workforce/attendance', 30, ['workcore.attendance'], 'Clocking, attendance state, leave and timesheets.'),
            'verification' => $section('workcore_workforce_verification', 'Attendance Verification', 'tabler-location-check', 'dashboard.user.workcore.workforce.verification.index', 'workforce/verification', 40, ['workcore.attendance.verification'], 'Location, evidence and assurance for attendance events.'),
            'assurance' => $section('workcore_workforce_assurance', 'Compliance and Assurance', 'tabler-certificate', 'dashboard.user.workcore.workforce.assurance.index', 'workforce/assurance', 50, ['workcore.compliance', 'workcore.assurance'], 'Skills, certifications, expiries and workforce assurance.'),
            'reports' => $section('workcore_workforce_reports', 'Workforce Reports', 'tabler-chart-dots', 'dashboard.user.workcore.workforce.reports.index', 'workforce/reports', 60, ['workcore.workforce'], 'Availability, attendance and workforce performance reporting.'),
        ],
    ),
    'resources' => $workspace(
        'workcore_resources_dropdown',
        'Resources',
        'tabler-building-warehouse',
        'dashboard.user.workcore.resources.index',
        'resources',
        70,
        ['workcore.premises'],
        'Premises, assets, fleet, inventory, supply and knowledge.',
        [
            'premises' => $section('workcore_resources_premises', 'Premises', 'tabler-building', 'dashboard.user.workcore.resources.premises.index', 'resources/premises', 10, ['workcore.premises'], 'Properties, service sites, spaces and occupancy context.'),
            'assets' => $section('workcore_resources_assets', 'Assets', 'tabler-tool', 'dashboard.user.workcore.resources.assets.index', 'resources/assets', 20, ['workcore.assets'], 'Customer, site and business assets and equipment.'),
            'fleet' => $section('workcore_resources_fleet', 'Fleet', 'tabler-truck', 'dashboard.user.workcore.resources.fleet.index', 'resources/fleet', 30, ['workcore.fleet'], 'Vehicles, allocation, maintenance and fleet readiness.'),
            'inventory' => $section('workcore_resources_inventory', 'Inventory', 'tabler-packages', 'dashboard.user.workcore.resources.inventory.index', 'resources/inventory', 40, ['workcore.inventory'], 'Stock, locations, material movements and reorder state.'),
            'supply' => $section('workcore_resources_supply', 'Suppliers and Supply', 'tabler-building-store', 'dashboard.user.workcore.resources.supply.index', 'resources/supply', 50, ['workcore.supply'], 'Suppliers, sourcing and operational supply records.'),
            'documents' => $section('workcore_resources_documents', 'Documents', 'tabler-files', 'dashboard.user.workcore.resources.documents.index', 'resources/documents', 60, ['workcore.documents'], 'Company and premise documents with governed retention.'),
            'knowledge' => $section('workcore_resources_knowledge', 'Knowledge Base', 'tabler-book-2', 'dashboard.user.workcore.resources.knowledge.index', 'resources/knowledge', 70, ['workcore.knowledge'], 'Operational knowledge, procedures and reusable guidance.'),
        ],
    ),
    'commercial' => $workspace(
        'workcore_commercial_dropdown',
        'Commercial',
        'tabler-receipt',
        'dashboard.user.workcore.commercial.index',
        'commercial',
        80,
        ['workcore.finance'],
        'Catalogue, quoting, invoicing, payments and operational finance.',
        [
            'catalogue' => $section('workcore_commercial_catalogue', 'Service Catalogue', 'tabler-list-details', 'dashboard.user.workcore.commercial.catalogue.index', 'commercial/catalogue', 10, ['workcore.catalogue'], 'Services, variants, pricing context and reusable scope definitions.'),
            'quotes' => $section('workcore_commercial_quotes', 'Quotes and Estimates', 'tabler-calculator', 'dashboard.user.workcore.commercial.quotes.index', 'commercial/quotes', 20, ['workcore.finance'], 'Versioned quotes, estimates, approvals and acceptance evidence.'),
            'invoices' => $section('workcore_commercial_invoices', 'Invoices', 'tabler-file-invoice', 'dashboard.user.workcore.commercial.invoices.index', 'commercial/invoices', 30, ['workcore.finance'], 'Customer invoices, lifecycle state and immutable snapshots.'),
            'receivables' => $section('workcore_commercial_receivables', 'Payments and Receivables', 'tabler-cash', 'dashboard.user.workcore.commercial.receivables.index', 'commercial/receivables', 40, ['workcore.finance'], 'Payments, allocations, evidence, receipts and collections.'),
            'expenses' => $section('workcore_commercial_expenses', 'Expenses and Payables', 'tabler-wallet', 'dashboard.user.workcore.commercial.expenses.index', 'commercial/expenses', 50, ['workcore.money.expense_claims'], 'Expenses, supplier obligations, approvals and payables.'),
            'procurement' => $section('workcore_commercial_procurement', 'Procurement', 'tabler-shopping-cart', 'dashboard.user.workcore.commercial.procurement.index', 'commercial/procurement', 60, ['workcore.money.procurement'], 'Purchase requests, orders and controlled procurement.'),
            'reconciliation' => $section('workcore_commercial_reconciliation', 'Reconciliation', 'tabler-arrows-exchange', 'dashboard.user.workcore.commercial.reconciliation.index', 'commercial/reconciliation', 70, ['workcore.finance'], 'Payment matching, bank reconciliation and financial controls.'),
            'profitability' => $section('workcore_commercial_profitability', 'Profitability', 'tabler-chart-line', 'dashboard.user.workcore.commercial.profitability.index', 'commercial/profitability', 80, ['workcore.finance'], 'Job costing, margins, forecasts and operational profitability.'),
        ],
    ),
];
