<?php

declare(strict_types=1);
namespace App\Domains\WorkCore\System\Modules\Finance\Repositories;
use App\Domains\WorkCore\System\Contracts\TenantContextContract;
use App\Domains\WorkCore\System\Modules\Finance\Contracts\PaymentOrchestrationRepositoryContract;
use App\Domains\WorkCore\System\Persistence\TenantScopedRepository;
use Illuminate\Database\ConnectionInterface;
use Illuminate\Support\Str;
use InvalidArgumentException;
final class EloquentPaymentOrchestrationRepository extends TenantScopedRepository implements PaymentOrchestrationRepositoryContract
{
    public function __construct(ConnectionInterface $db,TenantContextContract $tenant){parent::__construct($db,$tenant);}
    public function upsertProviderConnection(array $data,int $companyId,int $actorId):array{$this->guard($companyId,$actorId);$method=$this->required($data,'payment_method','method');$provider=$this->required($data,'provider_key','provider');$existing=$this->db->table('tm_payment_provider_connections')->where('company_id',(string)$companyId)->where('payment_method',$method)->where('provider_key',$provider)->first();$id=$existing?(string)$existing->id:(string)Str::uuid();$row=['id'=>$id,'company_id'=>(string)$companyId,'payment_method'=>$method,'provider_key'=>$provider,'connection_label'=>(string)($data['connection_label']??$provider),'state'=>(string)($data['state']??'active'),'configuration'=>json_encode($data['configuration']??$data['config']??[],JSON_THROW_ON_ERROR),'credentials_reference'=>$data['credentials_reference']??null,'updated_by_actor_id'=>(string)$actorId,'updated_at'=>now()];if($existing){$this->db->table('tm_payment_provider_connections')->where('id',$id)->update($row);}else{$row+=['created_by_actor_id'=>(string)$actorId,'created_at'=>now()];$this->db->table('tm_payment_provider_connections')->insert($row);}return $this->record('tm_payment_provider_connections',$id,$companyId);}
    public function createSession(array $data,int $companyId,int $actorId):array{$this->guard($companyId,$actorId);$token=bin2hex(random_bytes(32));$id=(string)Str::uuid();$currency=strtoupper((string)($data['currency_code']??$data['currency']??'AUD'));$amount=(int)($data['amount_minor']??0);if($amount<=0||strlen($currency)!==3)throw new InvalidArgumentException('A positive amount and currency are required.');$this->db->table('tm_payment_sessions')->insert(['id'=>$id,'company_id'=>(string)$companyId,'payment_request_id'=>$data['payment_request_id']??null,'provider_connection_id'=>$data['provider_connection_id']??null,'payment_method'=>$this->required($data,'payment_method','method'),'state'=>(string)($data['state']??'created'),'amount_minor'=>$amount,'currency_code'=>$currency,'session_token_hash'=>hash('sha256',$token),'provider_session_reference'=>$data['provider_session_reference']??null,'return_url'=>$data['return_url']??null,'expires_at'=>$data['expires_at']??now()->addMinutes(30),'metadata'=>json_encode($data['metadata']??[],JSON_THROW_ON_ERROR),'created_by_actor_id'=>(string)$actorId,'created_at'=>now(),'updated_at'=>now()]);$record=$this->record('tm_payment_sessions',$id,$companyId);$record['session_token']=$token;return $record;}
    public function recordAttempt(array $data,int $companyId,int $actorId):array{$this->guard($companyId,$actorId);$sessionId=$this->required($data,'session_id','payment_session_id');$this->record('tm_payment_sessions',$sessionId,$companyId);$id=(string)Str::uuid();$this->db->table('tm_payment_attempts')->insert(['id'=>$id,'company_id'=>(string)$companyId,'payment_session_id'=>$sessionId,'attempt_number'=>(int)($data['attempt_number']??($this->db->table('tm_payment_attempts')->where('company_id',(string)$companyId)->where('payment_session_id',$sessionId)->max('attempt_number')+1)),'state'=>(string)($data['state']??'initiated'),'provider_reference'=>$data['provider_reference']??null,'failure_code'=>$data['failure_code']??null,'failure_message'=>$data['failure_message']??null,'request_fingerprint'=>$data['request_fingerprint']??null,'response_metadata'=>json_encode($data['response_metadata']??[],JSON_THROW_ON_ERROR),'attempted_at'=>$data['attempted_at']??now(),'created_by_actor_id'=>(string)$actorId,'created_at'=>now(),'updated_at'=>now()]);if(isset($data['session_state']))$this->db->table('tm_payment_sessions')->where('company_id',(string)$companyId)->where('id',$sessionId)->update(['state'=>(string)$data['session_state'],'updated_at'=>now()]);return $this->record('tm_payment_attempts',$id,$companyId);}
    public function paymentSession(string $id,int $companyId):array{$session=$this->record('tm_payment_sessions',$id,$companyId);$session['attempts']=$this->db->table('tm_payment_attempts')->where('company_id',(string)$companyId)->where('payment_session_id',$id)->orderBy('attempt_number')->get()->map(fn($r)=>(array)$r)->all();unset($session['session_token_hash']);return $session;}
    public function summary(int $companyId):array{$c=(string)$companyId;return ['connections'=>(int)$this->db->table('tm_payment_provider_connections')->where('company_id',$c)->count(),'active_connections'=>(int)$this->db->table('tm_payment_provider_connections')->where('company_id',$c)->where('state','active')->count(),'sessions'=>(int)$this->db->table('tm_payment_sessions')->where('company_id',$c)->count(),'open_sessions'=>(int)$this->db->table('tm_payment_sessions')->where('company_id',$c)->whereIn('state',['created','pending','authorised'])->count(),'failed_attempts'=>(int)$this->db->table('tm_payment_attempts')->where('company_id',$c)->where('state','failed')->count()];}
    private function guard(int $c,int $a):void{if($c<1||$a<1)throw new InvalidArgumentException('Company and actor are required.');$this->assertCompany($c);}private function required(array $d,string ...$keys):string{foreach($keys as $k){$v=trim((string)($d[$k]??''));if($v!=='')return $v;}throw new InvalidArgumentException($keys[0].' is required.');}private function record(string $t,string $id,int $c):array{$r=$this->db->table($t)->where('company_id',(string)$c)->where('id',$id)->first();if(!$r)throw new InvalidArgumentException('Payment orchestration record was not found.');$a=(array)$r;$a['public_id']=$a['id']??$id;return $a;}
}
