<?php

return [
    'disclaimer' => 'Starter packs are operational templates only. They are not legal advice and must be checked against the current rules, licence conditions, contracts, insurer requirements, and local authority guidance that apply to the premise.',

    'packs' => [
        'generic_service_site_operations' => [
            'name' => 'Service Site Operational Review',
            'description' => 'Starter reminders for site access, hazards, and operational evidence.',
            'profile_key' => 'service_site',
            'jurisdiction_country' => null,
            'jurisdiction_region' => null,
            'version' => '1.0.0',
            'requires_local_verification' => true,
            'requirements' => [
                [
                    'key' => 'site_access_review',
                    'requirement_type' => 'access_review',
                    'title' => 'Review site access instructions',
                    'description' => 'Confirm access instructions, authorised contacts, restrictions, and emergency access remain current.',
                    'severity' => 'medium',
                    'recurrence_type' => 'months',
                    'recurrence_interval' => 6,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => false,
                ],
                [
                    'key' => 'hazard_register_review',
                    'requirement_type' => 'hazard_review',
                    'title' => 'Review premise hazard register',
                    'description' => 'Review recorded hazards and confirm controls, responsible parties, and linked work remain current.',
                    'severity' => 'high',
                    'recurrence_type' => 'months',
                    'recurrence_interval' => 6,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => true,
                    'evidence_types' => ['checklist', 'document', 'photo'],
                ],
            ],
        ],
        'generic_rooming_house_operations' => [
            'name' => 'Rooming House Compliance Framework',
            'description' => 'Unverified starter framework for registration, capacity, fire-safety evidence, emergency planning, and common-area reviews.',
            'profile_key' => 'rooming_house',
            'jurisdiction_country' => null,
            'jurisdiction_region' => null,
            'version' => '1.0.0',
            'requires_local_verification' => true,
            'requirements' => [
                [
                    'key' => 'registration_authority_review',
                    'requirement_type' => 'registration_review',
                    'title' => 'Review registration and authority evidence',
                    'description' => 'Confirm the current registration, licence, authority, or exemption evidence required for this premise and jurisdiction.',
                    'severity' => 'critical',
                    'recurrence_type' => 'annual',
                    'annual_month' => 7,
                    'annual_day' => 1,
                    'initial_due_offset_days' => 14,
                    'evidence_required' => true,
                    'evidence_types' => ['registration', 'licence', 'authority_document'],
                ],
                [
                    'key' => 'occupancy_capacity_review',
                    'requirement_type' => 'capacity_review',
                    'title' => 'Review occupancy and room-capacity register',
                    'description' => 'Compare actual occupancy and configured space capacity against the locally verified limits for the premise.',
                    'severity' => 'critical',
                    'recurrence_type' => 'months',
                    'recurrence_interval' => 3,
                    'initial_due_offset_days' => 14,
                    'evidence_required' => true,
                    'evidence_types' => ['occupancy_register', 'capacity_schedule'],
                ],
                [
                    'key' => 'fire_safety_evidence_review',
                    'requirement_type' => 'fire_safety_review',
                    'title' => 'Review fire-safety and essential-safety evidence',
                    'description' => 'Confirm required alarms, extinguishers, lighting, evacuation information, servicing, and evidence for the local jurisdiction.',
                    'severity' => 'critical',
                    'recurrence_type' => 'months',
                    'recurrence_interval' => 6,
                    'initial_due_offset_days' => 14,
                    'evidence_required' => true,
                    'evidence_types' => ['certificate', 'service_report', 'photo', 'document'],
                ],
                [
                    'key' => 'emergency_plan_review',
                    'requirement_type' => 'emergency_plan_review',
                    'title' => 'Review emergency plan and resident information',
                    'description' => 'Confirm emergency procedures, contacts, evacuation information, and resident-facing instructions remain current.',
                    'severity' => 'high',
                    'recurrence_type' => 'annual',
                    'annual_month' => 7,
                    'annual_day' => 1,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => true,
                    'evidence_types' => ['emergency_plan', 'resident_notice'],
                ],
            ],
        ],
        'generic_residential_property_operations' => [
            'name' => 'Residential Property Compliance Framework',
            'description' => 'Unverified starter framework for management authority, safety evidence, condition scheduling, and property-specific obligations.',
            'profile_key' => 'residential_rental',
            'jurisdiction_country' => null,
            'jurisdiction_region' => null,
            'version' => '1.0.0',
            'requires_local_verification' => true,
            'requirements' => [
                [
                    'key' => 'management_authority_review',
                    'requirement_type' => 'management_authority_review',
                    'title' => 'Review management authority and owner instructions',
                    'description' => 'Confirm the authority to manage, owner instructions, contact details, and approval boundaries remain current.',
                    'severity' => 'high',
                    'recurrence_type' => 'annual',
                    'annual_month' => 7,
                    'annual_day' => 1,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => true,
                    'evidence_types' => ['management_authority', 'owner_instruction'],
                ],
                [
                    'key' => 'property_safety_evidence_review',
                    'requirement_type' => 'property_safety_review',
                    'title' => 'Review property safety evidence',
                    'description' => 'Identify and verify the current local requirements for alarms, electrical, gas, pool barriers, and other property-specific safety duties.',
                    'severity' => 'critical',
                    'recurrence_type' => 'annual',
                    'annual_month' => 7,
                    'annual_day' => 1,
                    'initial_due_offset_days' => 14,
                    'evidence_required' => true,
                    'evidence_types' => ['certificate', 'service_report', 'inspection_report'],
                ],
                [
                    'key' => 'condition_schedule_review',
                    'requirement_type' => 'condition_schedule_review',
                    'title' => 'Review condition and inspection schedule',
                    'description' => 'Confirm entry, routine, and exit condition activities are scheduled according to the agreement and locally verified requirements.',
                    'severity' => 'medium',
                    'recurrence_type' => 'months',
                    'recurrence_interval' => 6,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => false,
                ],
            ],
        ],
        'generic_commercial_property_operations' => [
            'name' => 'Commercial Property Compliance Framework',
            'description' => 'Unverified starter framework for essential-safety evidence, insurance, access, and tenant-specific obligations.',
            'profile_key' => 'commercial_property',
            'jurisdiction_country' => null,
            'jurisdiction_region' => null,
            'version' => '1.0.0',
            'requires_local_verification' => true,
            'requirements' => [
                [
                    'key' => 'essential_safety_measure_review',
                    'requirement_type' => 'fire_safety_review',
                    'title' => 'Review essential-safety and fire-system evidence',
                    'description' => 'Identify the locally applicable essential-safety measures, servicing, records, and responsible parties for this property.',
                    'severity' => 'critical',
                    'recurrence_type' => 'months',
                    'recurrence_interval' => 6,
                    'initial_due_offset_days' => 14,
                    'evidence_required' => true,
                    'evidence_types' => ['certificate', 'service_report', 'inspection_report'],
                ],
                [
                    'key' => 'commercial_insurance_review',
                    'requirement_type' => 'insurance_review',
                    'title' => 'Review commercial-property insurance evidence',
                    'description' => 'Confirm current policy evidence, conditions, tenant obligations, and adviser instructions.',
                    'severity' => 'high',
                    'recurrence_type' => 'annual',
                    'annual_month' => 7,
                    'annual_day' => 1,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => true,
                    'evidence_types' => ['insurance_certificate', 'policy_schedule'],
                ],
                [
                    'key' => 'tenant_obligation_review',
                    'requirement_type' => 'contractual_obligation',
                    'title' => 'Review landlord and tenant compliance responsibilities',
                    'description' => 'Review the agreement and current local requirements to confirm who owns each inspection, certificate, repair, and evidence duty.',
                    'severity' => 'high',
                    'recurrence_type' => 'annual',
                    'annual_month' => 7,
                    'annual_day' => 1,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => true,
                    'evidence_types' => ['lease_schedule', 'responsibility_matrix'],
                ],
            ],
        ],
        'generic_storage_facility_operations' => [
            'name' => 'Storage Facility Compliance Framework',
            'description' => 'Unverified starter framework for emergency systems, access control, insurance evidence, and customer acknowledgements.',
            'profile_key' => 'storage_facility',
            'jurisdiction_country' => null,
            'jurisdiction_region' => null,
            'version' => '1.0.0',
            'requires_local_verification' => true,
            'requirements' => [
                [
                    'key' => 'fire_emergency_system_review',
                    'requirement_type' => 'fire_safety_review',
                    'title' => 'Review fire and emergency-system evidence',
                    'description' => 'Confirm the locally required fire systems, evacuation information, inspections, servicing, and evidence remain current.',
                    'severity' => 'critical',
                    'recurrence_type' => 'months',
                    'recurrence_interval' => 6,
                    'initial_due_offset_days' => 14,
                    'evidence_required' => true,
                    'evidence_types' => ['certificate', 'service_report', 'inspection_report'],
                ],
                [
                    'key' => 'access_control_review',
                    'requirement_type' => 'access_review',
                    'title' => 'Review gate, credential, and emergency-access controls',
                    'description' => 'Review active credentials, emergency access, revoked access, access hours, and custody exceptions.',
                    'severity' => 'high',
                    'recurrence_type' => 'months',
                    'recurrence_interval' => 6,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => true,
                    'evidence_types' => ['access_audit', 'system_report'],
                ],
                [
                    'key' => 'insurance_evidence_review',
                    'requirement_type' => 'insurance_review',
                    'title' => 'Review facility insurance evidence and conditions',
                    'description' => 'Confirm current facility insurance evidence, exclusions, and operational conditions with the responsible adviser or insurer.',
                    'severity' => 'high',
                    'recurrence_type' => 'annual',
                    'annual_month' => 7,
                    'annual_day' => 1,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => true,
                    'evidence_types' => ['insurance_certificate', 'policy_schedule'],
                ],
                [
                    'key' => 'customer_acknowledgement_review',
                    'requirement_type' => 'customer_acknowledgement_review',
                    'title' => 'Review prohibited-goods and customer acknowledgements',
                    'description' => 'Confirm current agreements and acknowledgements cover prohibited goods, access conditions, safety, and insurance responsibilities.',
                    'severity' => 'medium',
                    'recurrence_type' => 'annual',
                    'annual_month' => 7,
                    'annual_day' => 1,
                    'initial_due_offset_days' => 30,
                    'evidence_required' => true,
                    'evidence_types' => ['agreement_template', 'acknowledgement'],
                ],
            ],
        ],
    ],
];
