<?php

return [
    'token_bytes' => 32,
    'default_expiry_days' => 30,
    'allowed_capabilities' => [
        'view_premise_summary',
        'view_space_summary',
        'view_occupancy_summary',
        'view_agreement_summary',
        'view_workflow_progress',
        'view_access_authorisations',
        'submit_incident',
        'view_requests',
        'submit_request',
        'acknowledge_notice',
        'view_notices',
        'send_message',
        'view_messages',
        'view_owner_summary',
        'view_portfolio_summary',
        'view_approval_requests',
        'decide_approval_requests',
    ],
    'default_capabilities' => [
        'view_premise_summary',
        'view_space_summary',
        'view_occupancy_summary',
        'view_agreement_summary',
        'view_workflow_progress',
        'submit_incident',
        'view_messages',
        'send_message',
        'view_notices',
        'acknowledge_notice',
        'submit_request',
        'view_requests',
    ],
    'public_fields' => [
        'premise' => ['name', 'profile_key'],
        'space' => ['name', 'code', 'space_type', 'availability_status'],
        'occupancy' => ['status', 'occupancy_type', 'start_date', 'end_date', 'move_in_status', 'move_out_status'],
        'agreement' => ['title', 'agreement_type', 'status', 'start_date', 'end_date'],
    ],
    'forbidden_fields' => [
        'secret_value', 'token_hash', 'email', 'phone', 'finance_links', 'workcore_record_id',
        'billing_account_reference', 'deposit_reference', 'agreement_reference',
        'title_reference', 'titan_money_policy_reference', 'payload_snapshot',
    ],
];
