<?php

return [
    'default' => 'service_site',

    'premise_types' => [
        'house' => 'House',
        'rooming_house' => 'Rooming House',
        'apartment' => 'Apartment',
        'unit' => 'Unit',
        'building' => 'Building',
        'office' => 'Office',
        'office_centre' => 'Office Centre',
        'warehouse' => 'Warehouse',
        'storage_facility' => 'Storage Facility',
        'commercial_property' => 'Commercial Property',
        'strata_complex' => 'Strata Complex',
        'community_housing' => 'Community Housing',
        'caravan_park' => 'Caravan Park',
        'mixed_use' => 'Mixed Use',
        'jobsite' => 'Jobsite',
        'airbnb' => 'Short-Stay Property',
        'other' => 'Other',
    ],

    'profiles' => [
        'service_site' => [
            'label' => 'Service Site',
            'description' => 'Client premises, jobsites, cleaning sites, and field-service locations.',
            'terminology' => ['premise' => 'Site', 'space' => 'Area', 'occupant' => 'Client'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => false, 'agreements' => false, 'availability' => false, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'jobsite',
            'agreement_defaults' => ['type' => 'service_site_agreement'],
        ],
        'rooming_house' => [
            'label' => 'Rooming House',
            'description' => 'Rooming houses with residents, private rooms, shared areas, access, and compliance.',
            'terminology' => ['premise' => 'House', 'space' => 'Room', 'occupant' => 'Resident'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => true, 'availability' => true, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'rooming_house',
            'agreement_defaults' => ['type' => 'residency_agreement'],
        ],
        'residential_rental' => [
            'label' => 'Residential Real Estate',
            'description' => 'Residential rental properties managed for owners and tenants.',
            'terminology' => ['premise' => 'Property', 'space' => 'Unit', 'occupant' => 'Tenant'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => true, 'availability' => true, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'house',
            'agreement_defaults' => ['type' => 'residential_lease'],
        ],
        'commercial_property' => [
            'label' => 'Commercial Real Estate',
            'description' => 'Commercial buildings, suites, shops, warehouses, and business tenants.',
            'terminology' => ['premise' => 'Property', 'space' => 'Tenancy', 'occupant' => 'Tenant'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => true, 'availability' => true, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'commercial_property',
            'agreement_defaults' => ['type' => 'commercial_lease'],
        ],
        'strata_property' => [
            'label' => 'Strata Property',
            'description' => 'Strata complexes, lots, common property, owners, occupiers, and contractors.',
            'terminology' => ['premise' => 'Strata Property', 'space' => 'Lot', 'occupant' => 'Occupier'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => false, 'availability' => false, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'strata_complex',
            'agreement_defaults' => ['type' => 'owner_authority'],
        ],
        'storage_facility' => [
            'label' => 'Storage Facility',
            'description' => 'Storage facilities containing sheds, lockers, bays, cages, and customer allocations.',
            'terminology' => ['premise' => 'Facility', 'space' => 'Storage Unit', 'occupant' => 'Customer'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => true, 'availability' => true, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'storage_facility',
            'agreement_defaults' => ['type' => 'storage_agreement'],
        ],
        'warehouse' => [
            'label' => 'Warehouse',
            'description' => 'Warehouses, bays, zones, cages, stock areas, and allocated users.',
            'terminology' => ['premise' => 'Warehouse', 'space' => 'Zone', 'occupant' => 'User'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => false, 'availability' => true, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'warehouse',
            'agreement_defaults' => ['type' => 'internal_allocation'],
        ],
        'office_centre' => [
            'label' => 'Office Centre',
            'description' => 'Managed office centres, suites, desks, meeting rooms, and business occupiers.',
            'terminology' => ['premise' => 'Office Centre', 'space' => 'Suite', 'occupant' => 'Business'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => true, 'availability' => true, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'office_centre',
            'agreement_defaults' => ['type' => 'commercial_lease'],
        ],
        'community_housing' => [
            'label' => 'Community Housing',
            'description' => 'Community and supported housing with residents, support contacts, allocations, and compliance.',
            'terminology' => ['premise' => 'Property', 'space' => 'Dwelling', 'occupant' => 'Resident'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => true, 'availability' => true, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'community_housing',
            'agreement_defaults' => ['type' => 'residency_agreement'],
        ],
        'mixed_use' => [
            'label' => 'Mixed Use',
            'description' => 'Premises containing multiple residential, commercial, storage, or service uses.',
            'terminology' => ['premise' => 'Premise', 'space' => 'Space', 'occupant' => 'Occupant'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => true, 'agreements' => true, 'availability' => true, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'mixed_use',
            'agreement_defaults' => ['type' => 'custom'],
        ],
        'custom' => [
            'label' => 'Custom Premises',
            'description' => 'A configurable premises profile for a specialised operating model.',
            'terminology' => ['premise' => 'Premise', 'space' => 'Space', 'occupant' => 'Occupant'],
            'features' => ['operations' => true, 'service_plans' => true, 'visits' => true, 'occupancy' => false, 'agreements' => false, 'availability' => false, 'compliance' => true, 'access_register' => true, 'physical_access_cards' => true, 'work_permits' => true, 'condition_records' => true, 'incidents' => true],
            'default_type' => 'other',
            'agreement_defaults' => ['type' => 'custom'],
        ],
    ],
];
