<?php

declare(strict_types=1);
namespace App\Domains\WorkCore\System\Modules\Reviews\Repositories;
use App\Domains\WorkCore\System\Contracts\TenantContextContract;
use App\Domains\WorkCore\System\Modules\Reviews\Contracts\ReviewRepositoryContract;
use App\Domains\WorkCore\System\Modules\Reviews\Services\ReviewPolicy;
use App\Domains\WorkCore\System\Persistence\TenantScopedRepository;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\ConnectionInterface;
use Illuminate\Support\Str;
use InvalidArgumentException;
final class EloquentReviewRepository extends TenantScopedRepository implements ReviewRepositoryContract
{
    public function __construct(ConnectionInterface $db,TenantContextContract $tenant,private ReviewPolicy $policy){parent::__construct($db,$tenant);}
    public function search(int $companyId,array $filters=[],int $perPage=25): LengthAwarePaginator { $this->assertCompany($companyId);$q=$this->db->table('tz_reviews as r')->leftJoin('tz_customers as c','c.id','=','r.customer_id')->leftJoin('tz_premises as p','p.id','=','r.premises_id')->where('r.company_id',$companyId)->whereNull('r.deleted_at'); if(isset($filters['rating']))$q->where('r.rating',(int)$filters['rating']); if(!empty($filters['sentiment']))$q->where('r.sentiment',$filters['sentiment']); if(!empty($filters['publication_status']))$q->where('r.publication_status',$filters['publication_status']); return $q->select(['r.public_id','r.rating','r.sentiment','r.comment','r.public_permission','r.publication_status','r.published_at','r.created_at','c.public_id as customer_public_id','c.name as customer_name','p.public_id as premises_public_id','p.name as premises_name'])->orderByDesc('r.created_at')->paginate(max(1,min(100,$perPage))); }
    public function createRequest(array $d,int $companyId,int $actorId): array { $this->actor($companyId,$actorId);$refs=$this->refs($d,$companyId);$id=(string)Str::ulid();$this->db->table('tz_review_requests')->insert(array_merge(['public_id'=>$id,'company_id'=>$companyId,'audience'=>$d['audience']??'customer','channel'=>$d['channel']??'email','status'=>'requested','requested_at'=>now(),'expires_at'=>$d['expires_at']??null,'metadata'=>isset($d['metadata'])?json_encode($d['metadata'],JSON_THROW_ON_ERROR):null,'created_by_user_id'=>$actorId,'created_at'=>now(),'updated_at'=>now()],$refs));return (array)$this->db->table('tz_review_requests')->where('public_id',$id)->first(); }
    public function recordReview(array $d,int $companyId,int $actorId): array { $this->actor($companyId,$actorId);$rating=(int)$d['rating'];$sentiment=$this->policy->sentiment($rating);$refs=$this->refs($d,$companyId);$request=$this->record('tz_review_requests',$companyId,$d['review_request_public_id']??null);$id=(string)Str::ulid();return $this->db->transaction(function()use($d,$companyId,$actorId,$rating,$sentiment,$refs,$request,$id):array{$this->db->table('tz_reviews')->insert(array_merge(['public_id'=>$id,'company_id'=>$companyId,'review_request_id'=>$request?->id,'rating'=>$rating,'sentiment'=>$sentiment,'comment'=>$d['comment']??null,'public_permission'=>(bool)($d['public_permission']??false),'publication_status'=>'private','metadata'=>isset($d['metadata'])?json_encode($d['metadata'],JSON_THROW_ON_ERROR):null,'created_by_user_id'=>$actorId,'created_at'=>now(),'updated_at'=>now()],$refs));if($request)$this->db->table('tz_review_requests')->where('id',$request->id)->update(['status'=>'responded','responded_at'=>now(),'updated_at'=>now()]);$row=(array)$this->db->table('tz_reviews')->where('public_id',$id)->first();$row['requires_recovery']=$this->policy->requiresRecovery($rating);return $row;}); }
    public function publish(string $publicId,array $d,int $companyId,int $actorId): array { $this->actor($companyId,$actorId);$r=$this->record('tz_reviews',$companyId,$publicId,true);if(!$r)throw new InvalidArgumentException('Review does not belong to active company.');$status=(string)($d['status']??'published');$this->policy->assertPublication((bool)$r->public_permission,$status);$this->db->table('tz_reviews')->where('id',$r->id)->update(['publication_status'=>$status,'published_at'=>$status==='published'?now():null,'updated_at'=>now()]);$this->history($companyId,'review',(int)$r->id,(string)$r->publication_status,$status,$d['reason']??null,$actorId);return (array)$this->db->table('tz_reviews')->where('id',$r->id)->first(); }
    public function createRecovery(string $reviewPublicId,array $d,int $companyId,int $actorId): array { $this->actor($companyId,$actorId);$r=$this->record('tz_reviews',$companyId,$reviewPublicId,true);if(!$r)throw new InvalidArgumentException('Review does not belong to active company.');if(!$this->policy->requiresRecovery((int)$r->rating)&&empty($d['force']))throw new InvalidArgumentException('Service recovery is normally required only for ratings of two or lower.');$id=(string)Str::ulid();$this->db->table('tz_service_recovery_cases')->insert(['public_id'=>$id,'company_id'=>$companyId,'review_id'=>$r->id,'support_ticket_id'=>null,'work_order_id'=>null,'status'=>'open','severity'=>$d['severity']??((int)$r->rating===1?'high':'medium'),'reason'=>$d['reason']??($r->comment?:'Low review rating'),'assigned_user_id'=>$d['assigned_user_id']??null,'created_by_user_id'=>$actorId,'created_at'=>now(),'updated_at'=>now()]);return (array)$this->db->table('tz_service_recovery_cases')->where('public_id',$id)->first(); }
    public function requestRebooking(array $d,int $companyId,int $actorId): array { $this->actor($companyId,$actorId);$this->policy->assertRebookingWindow($d['preferred_start_at']??null,$d['preferred_end_at']??null);$refs=$this->refs($d,$companyId);$review=$this->record('tz_reviews',$companyId,$d['review_public_id']??null,true);$service=$this->record('tz_services',$companyId,$d['service_public_id']??null);$source=$this->record('tz_work_orders',$companyId,$d['source_work_order_public_id']??null);$id=(string)Str::ulid();$this->db->table('tz_rebooking_requests')->insert(['public_id'=>$id,'company_id'=>$companyId,'review_id'=>$review?->id,'customer_id'=>$refs['customer_id'],'premises_id'=>$refs['premises_id'],'service_id'=>$service?->id,'source_work_order_id'=>$source?->id,'status'=>'requested','preferred_start_at'=>$d['preferred_start_at']??null,'preferred_end_at'=>$d['preferred_end_at']??null,'timezone'=>$d['timezone']??config('workcore.context.default_timezone'),'notes'=>$d['notes']??null,'metadata'=>isset($d['metadata'])?json_encode($d['metadata'],JSON_THROW_ON_ERROR):null,'created_by_user_id'=>$actorId,'created_at'=>now(),'updated_at'=>now()]);return (array)$this->db->table('tz_rebooking_requests')->where('public_id',$id)->first(); }
    private function refs(array $d,int $companyId): array { return ['customer_id'=>$this->record('tz_customers',$companyId,$d['customer_public_id']??null)?->id,'contact_id'=>$this->record('tz_contacts',$companyId,$d['contact_public_id']??null)?->id,'premises_id'=>$this->record('tz_premises',$companyId,$d['premises_public_id']??null)?->id,'work_order_id'=>$this->record('tz_work_orders',$companyId,$d['work_order_public_id']??null)?->id,'appointment_id'=>$this->record('tz_appointments',$companyId,$d['appointment_public_id']??null)?->id,'worker_id'=>$this->record('tz_workers',$companyId,$d['worker_public_id']??null)?->id]; }
    private function record(string $table,int $companyId,mixed $publicId,bool $soft=false): ?object { if(!$publicId)return null;$q=$this->db->table($table)->where('company_id',$companyId)->where('public_id',(string)$publicId);if($soft)$q->whereNull('deleted_at');$r=$q->first();if(!$r)throw new InvalidArgumentException("Referenced {$table} record does not belong to active company.");return $r; }
    private function actor(int $companyId,int $actorId): void { $this->assertCompany($companyId);if($actorId<1||$actorId!==$this->actorId())throw new InvalidArgumentException('Review action actor does not match active user.'); }
    private function history(int $c,string $type,int $id,?string $from,string $to,?string $reason,int $actor): void {$this->db->table('tz_review_status_history')->insert(['public_id'=>(string)Str::ulid(),'company_id'=>$c,'subject_type'=>$type,'subject_id'=>$id,'from_status'=>$from,'to_status'=>$to,'reason'=>$reason,'actor_user_id'=>$actor,'changed_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);}
}
