@extends('layouts.app')
@section('content')
<div class="content-wrapper"><h4>Management authorities — {{ $property->name }}</h4><p class="text-muted">Operational authority metadata only. Titan Money owns monetary limits, balances and transactions.</p>@include('managedpremises::partials.property-tabs',['property'=>$property])
<div class="row"><div class="col-lg-5"><x-card><x-slot name="header">Create authority</x-slot><x-slot name="body"><x-form method="POST" :action="route('managedpremises.properties.management-authorities.store',$property->id)">@csrf
<div class="form-group"><label>Authorised party</label><select class="form-control" name="party_role_id" required>@foreach($parties as $party)<option value="{{ $party->id }}">{{ $party->display_name }} — {{ str($party->role)->replace('_',' ')->title() }}</option>@endforeach</select></div>
<div class="form-group"><label>Authority type</label><select class="form-control" name="authority_type">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseManagementAuthority::TYPES as $type)<option value="{{ $type }}">{{ str($type)->replace('_',' ')->title() }}</option>@endforeach</select></div>
<div class="form-row"><div class="form-group col"><label>Start</label><input class="form-control" type="date" name="start_date"></div><div class="form-group col"><label>End</label><input class="form-control" type="date" name="end_date"></div></div>
<div class="form-group"><label>Management agreement</label><select class="form-control" name="agreement_id"><option value="">—</option>@foreach($agreements as $agreement)<option value="{{ $agreement->id }}">{{ $agreement->title }}</option>@endforeach</select></div>
<div class="form-group"><label>Titan Money policy reference</label><input class="form-control" name="titan_money_policy_reference" maxlength="191"></div><button class="btn btn-primary" type="submit">Create draft</button></x-form></x-slot></x-card></div>
<div class="col-lg-7"><x-card><x-slot name="header">Authority register</x-slot><x-slot name="body">@forelse($authorities as $authority)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><strong>{{ $authority->partyRole?->display_name }}</strong><span class="badge badge-secondary">{{ str($authority->status)->replace('_',' ')->title() }}</span></div><div class="small text-muted">{{ str($authority->authority_type)->replace('_',' ')->title() }} · {{ optional($authority->start_date)->format('d M Y') ?: 'No start date' }}</div>@if(!in_array($authority->status,['ended','rejected','cancelled'],true))<x-form method="POST" :action="route('managedpremises.properties.management-authorities.transition',[$property->id,$authority->id])">@csrf<div class="form-row mt-2"><div class="col"><select class="form-control form-control-sm" name="status">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseManagementAuthority::STATUSES as $status)<option value="{{ $status }}">{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-sm btn-outline-primary">Transition</button></div></div></x-form>@endif</div>@empty<div class="text-muted">No management authorities.</div>@endforelse</x-slot></x-card></div></div></div>
@endsection
