@extends('layouts.app')
@section('content')
<div class="content-wrapper"><h4>Ownership — {{ $property->name }}</h4><p class="text-muted">Operational ownership register. Verify legal effect against source documents and local law.</p>@include('managedpremises::partials.property-tabs',['property'=>$property])
<div class="row"><div class="col-lg-5"><x-card><x-slot name="header">Add ownership interest</x-slot><x-slot name="body"><x-form method="POST" :action="route('managedpremises.properties.ownership.store',$property->id)">@csrf
<div class="form-group"><label>Owner</label><select class="form-control" name="party_role_id" required>@foreach($owners as $owner)<option value="{{ $owner->id }}">{{ $owner->display_name }}</option>@endforeach</select></div>
<div class="form-group"><label>Type</label><select class="form-control" name="ownership_type">@foreach(\App\Domains\WorkCore\System\Modules\Premises\Entities\PremiseOwnershipInterest::TYPES as $type)<option value="{{ $type }}">{{ str($type)->title() }}</option>@endforeach</select></div>
<div class="form-group"><label>Share %</label><input class="form-control" type="number" step="0.0001" min="0.0001" max="100" name="share_percent"></div>
<div class="form-group"><label>Valid from</label><input class="form-control" type="date" name="valid_from" value="{{ now()->toDateString() }}" required></div>
<div class="form-group"><label>Evidence document</label><select class="form-control" name="document_id"><option value="">—</option>@foreach($documents as $document)<option value="{{ $document->id }}">{{ $document->title ?? $document->name ?? ('Document #'.$document->id) }}</option>@endforeach</select></div>
<label><input type="checkbox" name="is_primary" value="1"> Primary owner</label><div class="form-group mt-2"><label>Notes</label><textarea class="form-control" name="notes" rows="3"></textarea></div><button class="btn btn-primary" type="submit">Add ownership</button></x-form></x-slot></x-card></div>
<div class="col-lg-7"><x-card><x-slot name="header">Ownership history</x-slot><x-slot name="body"><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Owner</th><th>Type</th><th>Share</th><th>Period</th><th></th></tr></thead><tbody>@forelse($interests as $interest)<tr><td>{{ $interest->partyRole?->display_name }} @if($interest->is_primary)<span class="badge badge-primary">Primary</span>@endif</td><td>{{ str($interest->ownership_type)->replace('_',' ')->title() }}</td><td>{{ $interest->share_percent !== null ? rtrim(rtrim(number_format((float)$interest->share_percent,4),'0'),'.').'%' : 'Unspecified' }}</td><td>{{ optional($interest->valid_from)->format('d M Y') }} – {{ optional($interest->valid_until)->format('d M Y') ?: 'Current' }}</td><td>@if(!$interest->valid_until)<x-form method="POST" :action="route('managedpremises.properties.ownership.end',[$property->id,$interest->id])">@csrf<button class="btn btn-sm btn-outline-danger">End</button></x-form>@endif</td></tr>@empty<tr><td colspan="5" class="text-muted">No ownership records.</td></tr>@endforelse</tbody></table></div></x-slot></x-card></div></div></div>
@endsection
